// Code generated by protoc-gen-go. DO NOT EDIT.
// source: owners.proto

package owners

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type BusinessOwner struct {
	BusinessOwnerID                int64    `protobuf:"varint,1,opt,name=businessOwnerID,proto3" json:"businessOwnerID,omitempty"`
	BusinessOwnerName              string   `protobuf:"bytes,2,opt,name=businessOwnerName,proto3" json:"businessOwnerName,omitempty"`
	BusinessOwnerEmail             string   `protobuf:"bytes,3,opt,name=businessOwnerEmail,proto3" json:"businessOwnerEmail,omitempty"`
	BusinessOwnerPhoneNumberPrefix string   `protobuf:"bytes,4,opt,name=businessOwnerPhoneNumberPrefix,proto3" json:"businessOwnerPhoneNumberPrefix,omitempty"`
	BusinessOwnerPhoneNumber       string   `protobuf:"bytes,5,opt,name=businessOwnerPhoneNumber,proto3" json:"businessOwnerPhoneNumber,omitempty"`
	XXX_NoUnkeyedLiteral           struct{} `json:"-"`
	XXX_unrecognized               []byte   `json:"-"`
	XXX_sizecache                  int32    `json:"-"`
}

func (m *BusinessOwner) Reset()         { *m = BusinessOwner{} }
func (m *BusinessOwner) String() string { return proto.CompactTextString(m) }
func (*BusinessOwner) ProtoMessage()    {}
func (*BusinessOwner) Descriptor() ([]byte, []int) {
	return fileDescriptor_6cadf282cb820384, []int{0}
}

func (m *BusinessOwner) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BusinessOwner.Unmarshal(m, b)
}
func (m *BusinessOwner) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BusinessOwner.Marshal(b, m, deterministic)
}
func (m *BusinessOwner) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BusinessOwner.Merge(m, src)
}
func (m *BusinessOwner) XXX_Size() int {
	return xxx_messageInfo_BusinessOwner.Size(m)
}
func (m *BusinessOwner) XXX_DiscardUnknown() {
	xxx_messageInfo_BusinessOwner.DiscardUnknown(m)
}

var xxx_messageInfo_BusinessOwner proto.InternalMessageInfo

func (m *BusinessOwner) GetBusinessOwnerID() int64 {
	if m != nil {
		return m.BusinessOwnerID
	}
	return 0
}

func (m *BusinessOwner) GetBusinessOwnerName() string {
	if m != nil {
		return m.BusinessOwnerName
	}
	return ""
}

func (m *BusinessOwner) GetBusinessOwnerEmail() string {
	if m != nil {
		return m.BusinessOwnerEmail
	}
	return ""
}

func (m *BusinessOwner) GetBusinessOwnerPhoneNumberPrefix() string {
	if m != nil {
		return m.BusinessOwnerPhoneNumberPrefix
	}
	return ""
}

func (m *BusinessOwner) GetBusinessOwnerPhoneNumber() string {
	if m != nil {
		return m.BusinessOwnerPhoneNumber
	}
	return ""
}

type CreateBusinessOwnerRequest struct {
	BusinessOwnerName              string   `protobuf:"bytes,1,opt,name=businessOwnerName,proto3" json:"businessOwnerName,omitempty"`
	BusinessOwnerEmail             string   `protobuf:"bytes,2,opt,name=businessOwnerEmail,proto3" json:"businessOwnerEmail,omitempty"`
	BusinessOwnerPassword          string   `protobuf:"bytes,3,opt,name=businessOwnerPassword,proto3" json:"businessOwnerPassword,omitempty"`
	BusinessOwnerPhoneNumberPrefix string   `protobuf:"bytes,4,opt,name=businessOwnerPhoneNumberPrefix,proto3" json:"businessOwnerPhoneNumberPrefix,omitempty"`
	BusinessOwnerPhoneNumber       string   `protobuf:"bytes,5,opt,name=businessOwnerPhoneNumber,proto3" json:"businessOwnerPhoneNumber,omitempty"`
	BusinessCompanyID              int64    `protobuf:"varint,6,opt,name=businessCompanyID,proto3" json:"businessCompanyID,omitempty"`
	XXX_NoUnkeyedLiteral           struct{} `json:"-"`
	XXX_unrecognized               []byte   `json:"-"`
	XXX_sizecache                  int32    `json:"-"`
}

func (m *CreateBusinessOwnerRequest) Reset()         { *m = CreateBusinessOwnerRequest{} }
func (m *CreateBusinessOwnerRequest) String() string { return proto.CompactTextString(m) }
func (*CreateBusinessOwnerRequest) ProtoMessage()    {}
func (*CreateBusinessOwnerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6cadf282cb820384, []int{1}
}

func (m *CreateBusinessOwnerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateBusinessOwnerRequest.Unmarshal(m, b)
}
func (m *CreateBusinessOwnerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateBusinessOwnerRequest.Marshal(b, m, deterministic)
}
func (m *CreateBusinessOwnerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateBusinessOwnerRequest.Merge(m, src)
}
func (m *CreateBusinessOwnerRequest) XXX_Size() int {
	return xxx_messageInfo_CreateBusinessOwnerRequest.Size(m)
}
func (m *CreateBusinessOwnerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateBusinessOwnerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateBusinessOwnerRequest proto.InternalMessageInfo

func (m *CreateBusinessOwnerRequest) GetBusinessOwnerName() string {
	if m != nil {
		return m.BusinessOwnerName
	}
	return ""
}

func (m *CreateBusinessOwnerRequest) GetBusinessOwnerEmail() string {
	if m != nil {
		return m.BusinessOwnerEmail
	}
	return ""
}

func (m *CreateBusinessOwnerRequest) GetBusinessOwnerPassword() string {
	if m != nil {
		return m.BusinessOwnerPassword
	}
	return ""
}

func (m *CreateBusinessOwnerRequest) GetBusinessOwnerPhoneNumberPrefix() string {
	if m != nil {
		return m.BusinessOwnerPhoneNumberPrefix
	}
	return ""
}

func (m *CreateBusinessOwnerRequest) GetBusinessOwnerPhoneNumber() string {
	if m != nil {
		return m.BusinessOwnerPhoneNumber
	}
	return ""
}

func (m *CreateBusinessOwnerRequest) GetBusinessCompanyID() int64 {
	if m != nil {
		return m.BusinessCompanyID
	}
	return 0
}

type CreateBusinessOwnerResponse struct {
	BusinessOwner        *BusinessOwner `protobuf:"bytes,1,opt,name=BusinessOwner,proto3" json:"BusinessOwner,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *CreateBusinessOwnerResponse) Reset()         { *m = CreateBusinessOwnerResponse{} }
func (m *CreateBusinessOwnerResponse) String() string { return proto.CompactTextString(m) }
func (*CreateBusinessOwnerResponse) ProtoMessage()    {}
func (*CreateBusinessOwnerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6cadf282cb820384, []int{2}
}

func (m *CreateBusinessOwnerResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateBusinessOwnerResponse.Unmarshal(m, b)
}
func (m *CreateBusinessOwnerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateBusinessOwnerResponse.Marshal(b, m, deterministic)
}
func (m *CreateBusinessOwnerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateBusinessOwnerResponse.Merge(m, src)
}
func (m *CreateBusinessOwnerResponse) XXX_Size() int {
	return xxx_messageInfo_CreateBusinessOwnerResponse.Size(m)
}
func (m *CreateBusinessOwnerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateBusinessOwnerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateBusinessOwnerResponse proto.InternalMessageInfo

func (m *CreateBusinessOwnerResponse) GetBusinessOwner() *BusinessOwner {
	if m != nil {
		return m.BusinessOwner
	}
	return nil
}

type BindCompanyToBusinessOwnerRequest struct {
	BusinessOwnerID      int64    `protobuf:"varint,1,opt,name=businessOwnerID,proto3" json:"businessOwnerID,omitempty"`
	BusinessCompanyID    int64    `protobuf:"varint,2,opt,name=businessCompanyID,proto3" json:"businessCompanyID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BindCompanyToBusinessOwnerRequest) Reset()         { *m = BindCompanyToBusinessOwnerRequest{} }
func (m *BindCompanyToBusinessOwnerRequest) String() string { return proto.CompactTextString(m) }
func (*BindCompanyToBusinessOwnerRequest) ProtoMessage()    {}
func (*BindCompanyToBusinessOwnerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6cadf282cb820384, []int{3}
}

func (m *BindCompanyToBusinessOwnerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BindCompanyToBusinessOwnerRequest.Unmarshal(m, b)
}
func (m *BindCompanyToBusinessOwnerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BindCompanyToBusinessOwnerRequest.Marshal(b, m, deterministic)
}
func (m *BindCompanyToBusinessOwnerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BindCompanyToBusinessOwnerRequest.Merge(m, src)
}
func (m *BindCompanyToBusinessOwnerRequest) XXX_Size() int {
	return xxx_messageInfo_BindCompanyToBusinessOwnerRequest.Size(m)
}
func (m *BindCompanyToBusinessOwnerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BindCompanyToBusinessOwnerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BindCompanyToBusinessOwnerRequest proto.InternalMessageInfo

func (m *BindCompanyToBusinessOwnerRequest) GetBusinessOwnerID() int64 {
	if m != nil {
		return m.BusinessOwnerID
	}
	return 0
}

func (m *BindCompanyToBusinessOwnerRequest) GetBusinessCompanyID() int64 {
	if m != nil {
		return m.BusinessCompanyID
	}
	return 0
}

type BindCompanyToBusinessOwnerResponse struct {
	BindSuccess          bool     `protobuf:"varint,1,opt,name=BindSuccess,proto3" json:"BindSuccess,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BindCompanyToBusinessOwnerResponse) Reset()         { *m = BindCompanyToBusinessOwnerResponse{} }
func (m *BindCompanyToBusinessOwnerResponse) String() string { return proto.CompactTextString(m) }
func (*BindCompanyToBusinessOwnerResponse) ProtoMessage()    {}
func (*BindCompanyToBusinessOwnerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6cadf282cb820384, []int{4}
}

func (m *BindCompanyToBusinessOwnerResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BindCompanyToBusinessOwnerResponse.Unmarshal(m, b)
}
func (m *BindCompanyToBusinessOwnerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BindCompanyToBusinessOwnerResponse.Marshal(b, m, deterministic)
}
func (m *BindCompanyToBusinessOwnerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BindCompanyToBusinessOwnerResponse.Merge(m, src)
}
func (m *BindCompanyToBusinessOwnerResponse) XXX_Size() int {
	return xxx_messageInfo_BindCompanyToBusinessOwnerResponse.Size(m)
}
func (m *BindCompanyToBusinessOwnerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BindCompanyToBusinessOwnerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BindCompanyToBusinessOwnerResponse proto.InternalMessageInfo

func (m *BindCompanyToBusinessOwnerResponse) GetBindSuccess() bool {
	if m != nil {
		return m.BindSuccess
	}
	return false
}

func init() {
	proto.RegisterType((*BusinessOwner)(nil), "businessOwners.BusinessOwner")
	proto.RegisterType((*CreateBusinessOwnerRequest)(nil), "businessOwners.CreateBusinessOwnerRequest")
	proto.RegisterType((*CreateBusinessOwnerResponse)(nil), "businessOwners.CreateBusinessOwnerResponse")
	proto.RegisterType((*BindCompanyToBusinessOwnerRequest)(nil), "businessOwners.BindCompanyToBusinessOwnerRequest")
	proto.RegisterType((*BindCompanyToBusinessOwnerResponse)(nil), "businessOwners.BindCompanyToBusinessOwnerResponse")
}

func init() { proto.RegisterFile("owners.proto", fileDescriptor_6cadf282cb820384) }

var fileDescriptor_6cadf282cb820384 = []byte{
	// 370 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x94, 0xcf, 0x4e, 0xc2, 0x40,
	0x10, 0xc6, 0x6d, 0x51, 0x82, 0x83, 0x7f, 0xe2, 0x1a, 0x93, 0x4d, 0x8d, 0x06, 0x7b, 0x22, 0x6a,
	0x9a, 0x88, 0x9e, 0x3c, 0x16, 0x24, 0xe1, 0x82, 0xa4, 0x78, 0xf2, 0xd6, 0xc2, 0x18, 0x9b, 0xd8,
	0x6e, 0xdd, 0xa1, 0xa2, 0xf1, 0xec, 0x1b, 0x78, 0xf3, 0xed, 0x7c, 0x12, 0xe3, 0x82, 0x91, 0x85,
	0x56, 0xc4, 0x93, 0xd7, 0x6f, 0xbe, 0xd9, 0x99, 0xf9, 0xcd, 0x64, 0x61, 0x4d, 0x0c, 0x63, 0x94,
	0xe4, 0x24, 0x52, 0x0c, 0x04, 0xdb, 0x08, 0x52, 0x0a, 0x63, 0x24, 0xba, 0x54, 0xaa, 0xfd, 0x66,
	0xc2, 0xba, 0x3b, 0x29, 0xb1, 0x2a, 0x6c, 0x6a, 0x9e, 0x56, 0x83, 0x1b, 0x15, 0xa3, 0x5a, 0xf0,
	0xa6, 0x65, 0x76, 0x0c, 0x5b, 0x9a, 0xd4, 0xf6, 0x23, 0xe4, 0x66, 0xc5, 0xa8, 0xae, 0x7a, 0xb3,
	0x01, 0xe6, 0x00, 0xd3, 0xc4, 0x8b, 0xc8, 0x0f, 0xef, 0x78, 0x41, 0xd9, 0x33, 0x22, 0xac, 0x09,
	0xfb, 0x9a, 0xda, 0xb9, 0x15, 0x31, 0xb6, 0xd3, 0x28, 0x40, 0xd9, 0x91, 0x78, 0x13, 0x3e, 0xf2,
	0x65, 0x95, 0x3b, 0xc7, 0xc5, 0xce, 0x81, 0xe7, 0x39, 0xf8, 0x8a, 0x7a, 0x21, 0x37, 0x6e, 0xbf,
	0x9b, 0x60, 0xd5, 0x25, 0xfa, 0x03, 0xd4, 0x18, 0x79, 0x78, 0x9f, 0x22, 0x0d, 0xb2, 0x01, 0x18,
	0x8b, 0x01, 0x30, 0x73, 0x01, 0x9c, 0xc1, 0x8e, 0xde, 0x98, 0x4f, 0x34, 0x14, 0xb2, 0x3f, 0x66,
	0x96, 0x1d, 0xfc, 0x0f, 0xd8, 0x26, 0xb9, 0xd4, 0x45, 0x94, 0xf8, 0xf1, 0x53, 0xab, 0xc1, 0x8b,
	0xea, 0x88, 0x66, 0x03, 0x76, 0x00, 0xbb, 0x99, 0x8c, 0x29, 0x11, 0x31, 0x21, 0xab, 0x4f, 0x1d,
	0xa8, 0x02, 0x5c, 0xae, 0xed, 0x39, 0xfa, 0x25, 0x3b, 0x7a, 0xb6, 0x9e, 0x63, 0x3f, 0xc3, 0x81,
	0x1b, 0xc6, 0xfd, 0x71, 0xd1, 0x2b, 0x91, 0xb9, 0xce, 0x3f, 0x5d, 0xfe, 0xf7, 0x80, 0x66, 0xde,
	0x80, 0x4d, 0xb0, 0x7f, 0x2a, 0x3e, 0x9e, 0xb3, 0x02, 0xe5, 0x4f, 0x57, 0x37, 0xed, 0xf5, 0x90,
	0x48, 0x55, 0x2e, 0x79, 0x93, 0x52, 0xed, 0xd5, 0x04, 0xee, 0x6a, 0xaf, 0x87, 0x48, 0x5d, 0x94,
	0x0f, 0x61, 0x0f, 0x59, 0x02, 0xdb, 0x19, 0x14, 0xd9, 0xe1, 0x34, 0xa6, 0xfc, 0x73, 0xb6, 0x8e,
	0x7e, 0xe5, 0x1d, 0xb5, 0x6b, 0x2f, 0xb1, 0x17, 0x03, 0xac, 0xfc, 0xb9, 0xd8, 0xc9, 0xcc, 0x82,
	0xe6, 0x2d, 0xc0, 0xaa, 0x2d, 0x92, 0xf2, 0xd5, 0x87, 0x5b, 0xba, 0x2e, 0x8e, 0xbe, 0xb8, 0xa0,
	0xa8, 0xfe, 0xb8, 0xd3, 0x8f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x2e, 0x64, 0x6f, 0x24, 0xf3, 0x04,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// BusinessCompaniesServiceClient is the client API for BusinessCompaniesService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BusinessCompaniesServiceClient interface {
	CreateBusinessOwner(ctx context.Context, in *CreateBusinessOwnerRequest, opts ...grpc.CallOption) (*CreateBusinessOwnerResponse, error)
	BindCompanyToBusinessOwner(ctx context.Context, in *BindCompanyToBusinessOwnerRequest, opts ...grpc.CallOption) (*BindCompanyToBusinessOwnerResponse, error)
}

type businessCompaniesServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBusinessCompaniesServiceClient(cc grpc.ClientConnInterface) BusinessCompaniesServiceClient {
	return &businessCompaniesServiceClient{cc}
}

func (c *businessCompaniesServiceClient) CreateBusinessOwner(ctx context.Context, in *CreateBusinessOwnerRequest, opts ...grpc.CallOption) (*CreateBusinessOwnerResponse, error) {
	out := new(CreateBusinessOwnerResponse)
	err := c.cc.Invoke(ctx, "/businessOwners.BusinessCompaniesService/CreateBusinessOwner", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *businessCompaniesServiceClient) BindCompanyToBusinessOwner(ctx context.Context, in *BindCompanyToBusinessOwnerRequest, opts ...grpc.CallOption) (*BindCompanyToBusinessOwnerResponse, error) {
	out := new(BindCompanyToBusinessOwnerResponse)
	err := c.cc.Invoke(ctx, "/businessOwners.BusinessCompaniesService/BindCompanyToBusinessOwner", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BusinessCompaniesServiceServer is the server API for BusinessCompaniesService service.
type BusinessCompaniesServiceServer interface {
	CreateBusinessOwner(context.Context, *CreateBusinessOwnerRequest) (*CreateBusinessOwnerResponse, error)
	BindCompanyToBusinessOwner(context.Context, *BindCompanyToBusinessOwnerRequest) (*BindCompanyToBusinessOwnerResponse, error)
}

// UnimplementedBusinessCompaniesServiceServer can be embedded to have forward compatible implementations.
type UnimplementedBusinessCompaniesServiceServer struct {
}

func (*UnimplementedBusinessCompaniesServiceServer) CreateBusinessOwner(ctx context.Context, req *CreateBusinessOwnerRequest) (*CreateBusinessOwnerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateBusinessOwner not implemented")
}
func (*UnimplementedBusinessCompaniesServiceServer) BindCompanyToBusinessOwner(ctx context.Context, req *BindCompanyToBusinessOwnerRequest) (*BindCompanyToBusinessOwnerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BindCompanyToBusinessOwner not implemented")
}

func RegisterBusinessCompaniesServiceServer(s *grpc.Server, srv BusinessCompaniesServiceServer) {
	s.RegisterService(&_BusinessCompaniesService_serviceDesc, srv)
}

func _BusinessCompaniesService_CreateBusinessOwner_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBusinessOwnerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BusinessCompaniesServiceServer).CreateBusinessOwner(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/businessOwners.BusinessCompaniesService/CreateBusinessOwner",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BusinessCompaniesServiceServer).CreateBusinessOwner(ctx, req.(*CreateBusinessOwnerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BusinessCompaniesService_BindCompanyToBusinessOwner_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BindCompanyToBusinessOwnerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BusinessCompaniesServiceServer).BindCompanyToBusinessOwner(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/businessOwners.BusinessCompaniesService/BindCompanyToBusinessOwner",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BusinessCompaniesServiceServer).BindCompanyToBusinessOwner(ctx, req.(*BindCompanyToBusinessOwnerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _BusinessCompaniesService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "businessOwners.BusinessCompaniesService",
	HandlerType: (*BusinessCompaniesServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateBusinessOwner",
			Handler:    _BusinessCompaniesService_CreateBusinessOwner_Handler,
		},
		{
			MethodName: "BindCompanyToBusinessOwner",
			Handler:    _BusinessCompaniesService_BindCompanyToBusinessOwner_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "owners.proto",
}
