// Code generated by protoc-gen-go. DO NOT EDIT.
// source: owners.proto

package owners

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type BusinessOwner struct {
	BusinessOwnerID                int64    `protobuf:"varint,1,opt,name=businessOwnerID,proto3" json:"businessOwnerID,omitempty"`
	BusinessOwnerName              string   `protobuf:"bytes,2,opt,name=businessOwnerName,proto3" json:"businessOwnerName,omitempty"`
	BusinessOwnerEmail             string   `protobuf:"bytes,3,opt,name=businessOwnerEmail,proto3" json:"businessOwnerEmail,omitempty"`
	BusinessOwnerPhoneNumberPrefix string   `protobuf:"bytes,4,opt,name=businessOwnerPhoneNumberPrefix,proto3" json:"businessOwnerPhoneNumberPrefix,omitempty"`
	BusinessOwnerPhoneNumber       string   `protobuf:"bytes,5,opt,name=businessOwnerPhoneNumber,proto3" json:"businessOwnerPhoneNumber,omitempty"`
	XXX_NoUnkeyedLiteral           struct{} `json:"-"`
	XXX_unrecognized               []byte   `json:"-"`
	XXX_sizecache                  int32    `json:"-"`
}

func (m *BusinessOwner) Reset()         { *m = BusinessOwner{} }
func (m *BusinessOwner) String() string { return proto.CompactTextString(m) }
func (*BusinessOwner) ProtoMessage()    {}
func (*BusinessOwner) Descriptor() ([]byte, []int) {
	return fileDescriptor_6cadf282cb820384, []int{0}
}

func (m *BusinessOwner) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BusinessOwner.Unmarshal(m, b)
}
func (m *BusinessOwner) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BusinessOwner.Marshal(b, m, deterministic)
}
func (m *BusinessOwner) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BusinessOwner.Merge(m, src)
}
func (m *BusinessOwner) XXX_Size() int {
	return xxx_messageInfo_BusinessOwner.Size(m)
}
func (m *BusinessOwner) XXX_DiscardUnknown() {
	xxx_messageInfo_BusinessOwner.DiscardUnknown(m)
}

var xxx_messageInfo_BusinessOwner proto.InternalMessageInfo

func (m *BusinessOwner) GetBusinessOwnerID() int64 {
	if m != nil {
		return m.BusinessOwnerID
	}
	return 0
}

func (m *BusinessOwner) GetBusinessOwnerName() string {
	if m != nil {
		return m.BusinessOwnerName
	}
	return ""
}

func (m *BusinessOwner) GetBusinessOwnerEmail() string {
	if m != nil {
		return m.BusinessOwnerEmail
	}
	return ""
}

func (m *BusinessOwner) GetBusinessOwnerPhoneNumberPrefix() string {
	if m != nil {
		return m.BusinessOwnerPhoneNumberPrefix
	}
	return ""
}

func (m *BusinessOwner) GetBusinessOwnerPhoneNumber() string {
	if m != nil {
		return m.BusinessOwnerPhoneNumber
	}
	return ""
}

type CreateBusinessOwnerRequest struct {
	BusinessOwnerName              string   `protobuf:"bytes,1,opt,name=businessOwnerName,proto3" json:"businessOwnerName,omitempty"`
	BusinessOwnerEmail             string   `protobuf:"bytes,2,opt,name=businessOwnerEmail,proto3" json:"businessOwnerEmail,omitempty"`
	BusinessOwnerPassword          string   `protobuf:"bytes,3,opt,name=businessOwnerPassword,proto3" json:"businessOwnerPassword,omitempty"`
	BusinessOwnerPhoneNumberPrefix string   `protobuf:"bytes,4,opt,name=businessOwnerPhoneNumberPrefix,proto3" json:"businessOwnerPhoneNumberPrefix,omitempty"`
	BusinessOwnerPhoneNumber       string   `protobuf:"bytes,5,opt,name=businessOwnerPhoneNumber,proto3" json:"businessOwnerPhoneNumber,omitempty"`
	BusinessCompanyID              int64    `protobuf:"varint,6,opt,name=businessCompanyID,proto3" json:"businessCompanyID,omitempty"`
	XXX_NoUnkeyedLiteral           struct{} `json:"-"`
	XXX_unrecognized               []byte   `json:"-"`
	XXX_sizecache                  int32    `json:"-"`
}

func (m *CreateBusinessOwnerRequest) Reset()         { *m = CreateBusinessOwnerRequest{} }
func (m *CreateBusinessOwnerRequest) String() string { return proto.CompactTextString(m) }
func (*CreateBusinessOwnerRequest) ProtoMessage()    {}
func (*CreateBusinessOwnerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6cadf282cb820384, []int{1}
}

func (m *CreateBusinessOwnerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateBusinessOwnerRequest.Unmarshal(m, b)
}
func (m *CreateBusinessOwnerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateBusinessOwnerRequest.Marshal(b, m, deterministic)
}
func (m *CreateBusinessOwnerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateBusinessOwnerRequest.Merge(m, src)
}
func (m *CreateBusinessOwnerRequest) XXX_Size() int {
	return xxx_messageInfo_CreateBusinessOwnerRequest.Size(m)
}
func (m *CreateBusinessOwnerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateBusinessOwnerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateBusinessOwnerRequest proto.InternalMessageInfo

func (m *CreateBusinessOwnerRequest) GetBusinessOwnerName() string {
	if m != nil {
		return m.BusinessOwnerName
	}
	return ""
}

func (m *CreateBusinessOwnerRequest) GetBusinessOwnerEmail() string {
	if m != nil {
		return m.BusinessOwnerEmail
	}
	return ""
}

func (m *CreateBusinessOwnerRequest) GetBusinessOwnerPassword() string {
	if m != nil {
		return m.BusinessOwnerPassword
	}
	return ""
}

func (m *CreateBusinessOwnerRequest) GetBusinessOwnerPhoneNumberPrefix() string {
	if m != nil {
		return m.BusinessOwnerPhoneNumberPrefix
	}
	return ""
}

func (m *CreateBusinessOwnerRequest) GetBusinessOwnerPhoneNumber() string {
	if m != nil {
		return m.BusinessOwnerPhoneNumber
	}
	return ""
}

func (m *CreateBusinessOwnerRequest) GetBusinessCompanyID() int64 {
	if m != nil {
		return m.BusinessCompanyID
	}
	return 0
}

type CreateBusinessOwnerResponse struct {
	BusinessOwner        *BusinessOwner `protobuf:"bytes,1,opt,name=BusinessOwner,proto3" json:"BusinessOwner,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *CreateBusinessOwnerResponse) Reset()         { *m = CreateBusinessOwnerResponse{} }
func (m *CreateBusinessOwnerResponse) String() string { return proto.CompactTextString(m) }
func (*CreateBusinessOwnerResponse) ProtoMessage()    {}
func (*CreateBusinessOwnerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6cadf282cb820384, []int{2}
}

func (m *CreateBusinessOwnerResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateBusinessOwnerResponse.Unmarshal(m, b)
}
func (m *CreateBusinessOwnerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateBusinessOwnerResponse.Marshal(b, m, deterministic)
}
func (m *CreateBusinessOwnerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateBusinessOwnerResponse.Merge(m, src)
}
func (m *CreateBusinessOwnerResponse) XXX_Size() int {
	return xxx_messageInfo_CreateBusinessOwnerResponse.Size(m)
}
func (m *CreateBusinessOwnerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateBusinessOwnerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateBusinessOwnerResponse proto.InternalMessageInfo

func (m *CreateBusinessOwnerResponse) GetBusinessOwner() *BusinessOwner {
	if m != nil {
		return m.BusinessOwner
	}
	return nil
}

type BindCompanyToBusinessOwnerRequest struct {
	BusinessOwnerID      int64    `protobuf:"varint,1,opt,name=businessOwnerID,proto3" json:"businessOwnerID,omitempty"`
	BusinessCompanyID    int64    `protobuf:"varint,2,opt,name=businessCompanyID,proto3" json:"businessCompanyID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BindCompanyToBusinessOwnerRequest) Reset()         { *m = BindCompanyToBusinessOwnerRequest{} }
func (m *BindCompanyToBusinessOwnerRequest) String() string { return proto.CompactTextString(m) }
func (*BindCompanyToBusinessOwnerRequest) ProtoMessage()    {}
func (*BindCompanyToBusinessOwnerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6cadf282cb820384, []int{3}
}

func (m *BindCompanyToBusinessOwnerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BindCompanyToBusinessOwnerRequest.Unmarshal(m, b)
}
func (m *BindCompanyToBusinessOwnerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BindCompanyToBusinessOwnerRequest.Marshal(b, m, deterministic)
}
func (m *BindCompanyToBusinessOwnerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BindCompanyToBusinessOwnerRequest.Merge(m, src)
}
func (m *BindCompanyToBusinessOwnerRequest) XXX_Size() int {
	return xxx_messageInfo_BindCompanyToBusinessOwnerRequest.Size(m)
}
func (m *BindCompanyToBusinessOwnerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BindCompanyToBusinessOwnerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BindCompanyToBusinessOwnerRequest proto.InternalMessageInfo

func (m *BindCompanyToBusinessOwnerRequest) GetBusinessOwnerID() int64 {
	if m != nil {
		return m.BusinessOwnerID
	}
	return 0
}

func (m *BindCompanyToBusinessOwnerRequest) GetBusinessCompanyID() int64 {
	if m != nil {
		return m.BusinessCompanyID
	}
	return 0
}

type BindCompanyToBusinessOwnerResponse struct {
	BindSuccess          bool     `protobuf:"varint,1,opt,name=BindSuccess,proto3" json:"BindSuccess,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BindCompanyToBusinessOwnerResponse) Reset()         { *m = BindCompanyToBusinessOwnerResponse{} }
func (m *BindCompanyToBusinessOwnerResponse) String() string { return proto.CompactTextString(m) }
func (*BindCompanyToBusinessOwnerResponse) ProtoMessage()    {}
func (*BindCompanyToBusinessOwnerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6cadf282cb820384, []int{4}
}

func (m *BindCompanyToBusinessOwnerResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BindCompanyToBusinessOwnerResponse.Unmarshal(m, b)
}
func (m *BindCompanyToBusinessOwnerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BindCompanyToBusinessOwnerResponse.Marshal(b, m, deterministic)
}
func (m *BindCompanyToBusinessOwnerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BindCompanyToBusinessOwnerResponse.Merge(m, src)
}
func (m *BindCompanyToBusinessOwnerResponse) XXX_Size() int {
	return xxx_messageInfo_BindCompanyToBusinessOwnerResponse.Size(m)
}
func (m *BindCompanyToBusinessOwnerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BindCompanyToBusinessOwnerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BindCompanyToBusinessOwnerResponse proto.InternalMessageInfo

func (m *BindCompanyToBusinessOwnerResponse) GetBindSuccess() bool {
	if m != nil {
		return m.BindSuccess
	}
	return false
}

func init() {
	proto.RegisterType((*BusinessOwner)(nil), "businessOwners.BusinessOwner")
	proto.RegisterType((*CreateBusinessOwnerRequest)(nil), "businessOwners.CreateBusinessOwnerRequest")
	proto.RegisterType((*CreateBusinessOwnerResponse)(nil), "businessOwners.CreateBusinessOwnerResponse")
	proto.RegisterType((*BindCompanyToBusinessOwnerRequest)(nil), "businessOwners.BindCompanyToBusinessOwnerRequest")
	proto.RegisterType((*BindCompanyToBusinessOwnerResponse)(nil), "businessOwners.BindCompanyToBusinessOwnerResponse")
}

func init() { proto.RegisterFile("owners.proto", fileDescriptor_6cadf282cb820384) }

var fileDescriptor_6cadf282cb820384 = []byte{
	// 368 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x94, 0x4f, 0x4f, 0xf2, 0x40,
	0x10, 0xc6, 0xdf, 0x96, 0x57, 0x82, 0x83, 0x7f, 0xe2, 0xa8, 0xc9, 0xa6, 0x46, 0x83, 0x3d, 0x11,
	0x35, 0x4d, 0x44, 0x4f, 0x1e, 0x01, 0x49, 0xb8, 0x20, 0x29, 0x9e, 0xbc, 0xb5, 0x30, 0xc6, 0x26,
	0xb6, 0x5b, 0x77, 0xa9, 0x68, 0x3c, 0x7b, 0xf7, 0xee, 0xb7, 0xf3, 0x93, 0x18, 0x17, 0x8c, 0x2c,
	0x6d, 0x45, 0x3c, 0x79, 0x7d, 0xe6, 0x99, 0xce, 0xcc, 0xaf, 0x4f, 0x16, 0x56, 0xf8, 0x28, 0x22,
	0x21, 0x9d, 0x58, 0xf0, 0x21, 0xc7, 0x35, 0x3f, 0x91, 0x41, 0x44, 0x52, 0x5e, 0x28, 0xd5, 0x7e,
	0x35, 0x61, 0xb5, 0x3e, 0x2d, 0x61, 0x15, 0xd6, 0x35, 0x4f, 0xbb, 0xc9, 0x8c, 0x8a, 0x51, 0x2d,
	0xb8, 0xb3, 0x32, 0x1e, 0xc1, 0x86, 0x26, 0x75, 0xbc, 0x90, 0x98, 0x59, 0x31, 0xaa, 0xcb, 0x6e,
	0xba, 0x80, 0x0e, 0xa0, 0x26, 0x9e, 0x87, 0x5e, 0x70, 0xcb, 0x0a, 0xca, 0x9e, 0x51, 0xc1, 0x16,
	0xec, 0x69, 0x6a, 0xf7, 0x86, 0x47, 0xd4, 0x49, 0x42, 0x9f, 0x44, 0x57, 0xd0, 0x75, 0xf0, 0xc0,
	0xfe, 0xab, 0xde, 0x39, 0x2e, 0x3c, 0x03, 0x96, 0xe7, 0x60, 0x4b, 0xea, 0x0b, 0xb9, 0x75, 0xfb,
	0xcd, 0x04, 0xab, 0x21, 0xc8, 0x1b, 0x92, 0xc6, 0xc8, 0xa5, 0xbb, 0x84, 0xe4, 0x30, 0x1b, 0x80,
	0xb1, 0x18, 0x00, 0x33, 0x17, 0xc0, 0x29, 0x6c, 0xeb, 0x8b, 0x79, 0x52, 0x8e, 0xb8, 0x18, 0x4c,
	0x98, 0x65, 0x17, 0xff, 0x02, 0xb6, 0x69, 0x2e, 0x0d, 0x1e, 0xc6, 0x5e, 0xf4, 0xd8, 0x6e, 0xb2,
	0xa2, 0x0a, 0x51, 0xba, 0x60, 0xfb, 0xb0, 0x93, 0xc9, 0x58, 0xc6, 0x3c, 0x92, 0x84, 0x8d, 0x99,
	0x80, 0x2a, 0xc0, 0xe5, 0xda, 0xae, 0xa3, 0x27, 0xd9, 0xd1, 0xbb, 0xf5, 0x1e, 0xfb, 0x09, 0xf6,
	0xeb, 0x41, 0x34, 0x98, 0x0c, 0xbd, 0xe4, 0x99, 0xbf, 0xf3, 0x57, 0xc9, 0xff, 0x3a, 0xd0, 0xcc,
	0x3b, 0xb0, 0x05, 0xf6, 0x77, 0xc3, 0x27, 0x77, 0x56, 0xa0, 0xfc, 0xe1, 0xea, 0x25, 0xfd, 0x3e,
	0x49, 0xa9, 0x26, 0x97, 0xdc, 0x69, 0xa9, 0xf6, 0x62, 0xc2, 0x96, 0xd6, 0xdb, 0x23, 0x71, 0x1f,
	0xf4, 0x09, 0x63, 0xd8, 0xcc, 0x20, 0x88, 0x07, 0xb3, 0x88, 0xf2, 0xa3, 0x6c, 0x1d, 0xfe, 0xc8,
	0x3b, 0x5e, 0xd5, 0xfe, 0x87, 0xcf, 0x06, 0x58, 0xf9, 0x37, 0xe1, 0x71, 0xea, 0xe7, 0xcc, 0x83,
	0x6f, 0xd5, 0x16, 0x69, 0xf9, 0xdc, 0xa3, 0x5e, 0xba, 0x2a, 0x8e, 0x9f, 0x37, 0xbf, 0xa8, 0xde,
	0xb7, 0x93, 0xf7, 0x00, 0x00, 0x00, 0xff, 0xff, 0xfc, 0x77, 0x63, 0x51, 0xef, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// BusinessOwnerServiceClient is the client API for BusinessOwnerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BusinessOwnerServiceClient interface {
	CreateBusinessOwner(ctx context.Context, in *CreateBusinessOwnerRequest, opts ...grpc.CallOption) (*CreateBusinessOwnerResponse, error)
	BindCompanyToBusinessOwner(ctx context.Context, in *BindCompanyToBusinessOwnerRequest, opts ...grpc.CallOption) (*BindCompanyToBusinessOwnerResponse, error)
}

type businessOwnerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBusinessOwnerServiceClient(cc grpc.ClientConnInterface) BusinessOwnerServiceClient {
	return &businessOwnerServiceClient{cc}
}

func (c *businessOwnerServiceClient) CreateBusinessOwner(ctx context.Context, in *CreateBusinessOwnerRequest, opts ...grpc.CallOption) (*CreateBusinessOwnerResponse, error) {
	out := new(CreateBusinessOwnerResponse)
	err := c.cc.Invoke(ctx, "/businessOwners.BusinessOwnerService/CreateBusinessOwner", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *businessOwnerServiceClient) BindCompanyToBusinessOwner(ctx context.Context, in *BindCompanyToBusinessOwnerRequest, opts ...grpc.CallOption) (*BindCompanyToBusinessOwnerResponse, error) {
	out := new(BindCompanyToBusinessOwnerResponse)
	err := c.cc.Invoke(ctx, "/businessOwners.BusinessOwnerService/BindCompanyToBusinessOwner", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BusinessOwnerServiceServer is the server API for BusinessOwnerService service.
type BusinessOwnerServiceServer interface {
	CreateBusinessOwner(context.Context, *CreateBusinessOwnerRequest) (*CreateBusinessOwnerResponse, error)
	BindCompanyToBusinessOwner(context.Context, *BindCompanyToBusinessOwnerRequest) (*BindCompanyToBusinessOwnerResponse, error)
}

// UnimplementedBusinessOwnerServiceServer can be embedded to have forward compatible implementations.
type UnimplementedBusinessOwnerServiceServer struct {
}

func (*UnimplementedBusinessOwnerServiceServer) CreateBusinessOwner(ctx context.Context, req *CreateBusinessOwnerRequest) (*CreateBusinessOwnerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateBusinessOwner not implemented")
}
func (*UnimplementedBusinessOwnerServiceServer) BindCompanyToBusinessOwner(ctx context.Context, req *BindCompanyToBusinessOwnerRequest) (*BindCompanyToBusinessOwnerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BindCompanyToBusinessOwner not implemented")
}

func RegisterBusinessOwnerServiceServer(s *grpc.Server, srv BusinessOwnerServiceServer) {
	s.RegisterService(&_BusinessOwnerService_serviceDesc, srv)
}

func _BusinessOwnerService_CreateBusinessOwner_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBusinessOwnerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BusinessOwnerServiceServer).CreateBusinessOwner(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/businessOwners.BusinessOwnerService/CreateBusinessOwner",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BusinessOwnerServiceServer).CreateBusinessOwner(ctx, req.(*CreateBusinessOwnerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BusinessOwnerService_BindCompanyToBusinessOwner_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BindCompanyToBusinessOwnerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BusinessOwnerServiceServer).BindCompanyToBusinessOwner(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/businessOwners.BusinessOwnerService/BindCompanyToBusinessOwner",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BusinessOwnerServiceServer).BindCompanyToBusinessOwner(ctx, req.(*BindCompanyToBusinessOwnerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _BusinessOwnerService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "businessOwners.BusinessOwnerService",
	HandlerType: (*BusinessOwnerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateBusinessOwner",
			Handler:    _BusinessOwnerService_CreateBusinessOwner_Handler,
		},
		{
			MethodName: "BindCompanyToBusinessOwner",
			Handler:    _BusinessOwnerService_BindCompanyToBusinessOwner_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "owners.proto",
}
