version: '3'
services:
  qaqtus.me:
    build:
      context: .
      dockerfile: ./services/server/Dockerfile
    ports:
      - "50051:50051"
  client:
    build:
      context: .
      dockerfile: ./api/graphQL/Dockerfile
    links:
      - qaqtus.me
    ports:
        - "8080:8080"