// Code generated by protoc-gen-go. DO NOT EDIT.
// source: email.proto

package email

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type BusinessOwnerEmail struct {
	Address              string   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BusinessOwnerEmail) Reset()         { *m = BusinessOwnerEmail{} }
func (m *BusinessOwnerEmail) String() string { return proto.CompactTextString(m) }
func (*BusinessOwnerEmail) ProtoMessage()    {}
func (*BusinessOwnerEmail) Descriptor() ([]byte, []int) {
	return fileDescriptor_6175298cb4ed6faa, []int{0}
}

func (m *BusinessOwnerEmail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BusinessOwnerEmail.Unmarshal(m, b)
}
func (m *BusinessOwnerEmail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BusinessOwnerEmail.Marshal(b, m, deterministic)
}
func (m *BusinessOwnerEmail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BusinessOwnerEmail.Merge(m, src)
}
func (m *BusinessOwnerEmail) XXX_Size() int {
	return xxx_messageInfo_BusinessOwnerEmail.Size(m)
}
func (m *BusinessOwnerEmail) XXX_DiscardUnknown() {
	xxx_messageInfo_BusinessOwnerEmail.DiscardUnknown(m)
}

var xxx_messageInfo_BusinessOwnerEmail proto.InternalMessageInfo

func (m *BusinessOwnerEmail) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type BusinessOwnerEmailRequest struct {
	Email                *BusinessOwnerEmail `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *BusinessOwnerEmailRequest) Reset()         { *m = BusinessOwnerEmailRequest{} }
func (m *BusinessOwnerEmailRequest) String() string { return proto.CompactTextString(m) }
func (*BusinessOwnerEmailRequest) ProtoMessage()    {}
func (*BusinessOwnerEmailRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6175298cb4ed6faa, []int{1}
}

func (m *BusinessOwnerEmailRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BusinessOwnerEmailRequest.Unmarshal(m, b)
}
func (m *BusinessOwnerEmailRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BusinessOwnerEmailRequest.Marshal(b, m, deterministic)
}
func (m *BusinessOwnerEmailRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BusinessOwnerEmailRequest.Merge(m, src)
}
func (m *BusinessOwnerEmailRequest) XXX_Size() int {
	return xxx_messageInfo_BusinessOwnerEmailRequest.Size(m)
}
func (m *BusinessOwnerEmailRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BusinessOwnerEmailRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BusinessOwnerEmailRequest proto.InternalMessageInfo

func (m *BusinessOwnerEmailRequest) GetEmail() *BusinessOwnerEmail {
	if m != nil {
		return m.Email
	}
	return nil
}

func init() {
	proto.RegisterType((*BusinessOwnerEmail)(nil), "email.BusinessOwnerEmail")
	proto.RegisterType((*BusinessOwnerEmailRequest)(nil), "email.BusinessOwnerEmailRequest")
}

func init() { proto.RegisterFile("email.proto", fileDescriptor_6175298cb4ed6faa) }

var fileDescriptor_6175298cb4ed6faa = []byte{
	// 191 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4e, 0xcd, 0x4d, 0xcc,
	0xcc, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x73, 0xa4, 0xa4, 0xd3, 0xf3, 0xf3,
	0xd3, 0x73, 0x52, 0xf5, 0xc1, 0x82, 0x49, 0xa5, 0x69, 0xfa, 0xa9, 0xb9, 0x05, 0x25, 0x95, 0x10,
	0x35, 0x4a, 0x7a, 0x5c, 0x42, 0x4e, 0xa5, 0xc5, 0x99, 0x79, 0xa9, 0xc5, 0xc5, 0xfe, 0xe5, 0x79,
	0xa9, 0x45, 0xae, 0x20, 0x2d, 0x42, 0x12, 0x5c, 0xec, 0x89, 0x29, 0x29, 0x45, 0xa9, 0xc5, 0xc5,
	0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x30, 0xae, 0x92, 0x0f, 0x97, 0x24, 0xa6, 0xfa, 0xa0,
	0xd4, 0xc2, 0xd2, 0xd4, 0xe2, 0x12, 0x21, 0x7d, 0x2e, 0x88, 0x95, 0x60, 0x4d, 0xdc, 0x46, 0x92,
	0x7a, 0x10, 0xd7, 0x60, 0xd1, 0x00, 0x51, 0x67, 0x94, 0xc6, 0xc5, 0x03, 0xe6, 0x07, 0xa7, 0x16,
	0x95, 0x65, 0x26, 0xa7, 0x0a, 0x85, 0x71, 0x49, 0x04, 0xa7, 0xe6, 0xa5, 0x80, 0xc5, 0x42, 0xf2,
	0x51, 0xf4, 0x09, 0x29, 0xe0, 0x36, 0x0d, 0x62, 0xbd, 0x94, 0x98, 0x1e, 0xc4, 0xa7, 0x7a, 0x30,
	0x9f, 0xea, 0xb9, 0x82, 0x7c, 0xaa, 0xc4, 0xe0, 0xc4, 0x1e, 0x05, 0xb1, 0x30, 0x89, 0x0d, 0x2c,
	0x65, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x8d, 0x73, 0x1c, 0xe4, 0x28, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// EmailServiceClient is the client API for EmailService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type EmailServiceClient interface {
	SendEmailToBusinessOwner(ctx context.Context, in *BusinessOwnerEmailRequest, opts ...grpc.CallOption) (*empty.Empty, error)
}

type emailServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEmailServiceClient(cc grpc.ClientConnInterface) EmailServiceClient {
	return &emailServiceClient{cc}
}

func (c *emailServiceClient) SendEmailToBusinessOwner(ctx context.Context, in *BusinessOwnerEmailRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/email.EmailService/SendEmailToBusinessOwner", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EmailServiceServer is the server API for EmailService service.
type EmailServiceServer interface {
	SendEmailToBusinessOwner(context.Context, *BusinessOwnerEmailRequest) (*empty.Empty, error)
}

// UnimplementedEmailServiceServer can be embedded to have forward compatible implementations.
type UnimplementedEmailServiceServer struct {
}

func (*UnimplementedEmailServiceServer) SendEmailToBusinessOwner(ctx context.Context, req *BusinessOwnerEmailRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendEmailToBusinessOwner not implemented")
}

func RegisterEmailServiceServer(s *grpc.Server, srv EmailServiceServer) {
	s.RegisterService(&_EmailService_serviceDesc, srv)
}

func _EmailService_SendEmailToBusinessOwner_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BusinessOwnerEmailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmailServiceServer).SendEmailToBusinessOwner(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/email.EmailService/SendEmailToBusinessOwner",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmailServiceServer).SendEmailToBusinessOwner(ctx, req.(*BusinessOwnerEmailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _EmailService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "email.EmailService",
	HandlerType: (*EmailServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendEmailToBusinessOwner",
			Handler:    _EmailService_SendEmailToBusinessOwner_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "email.proto",
}
