// Code generated by protoc-gen-go. DO NOT EDIT.
// source: subCategories.proto

package subCategories

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type BusinessSubCategory struct {
	BusinessSubCategoryID   int64    `protobuf:"varint,1,opt,name=businessSubCategoryID,proto3" json:"businessSubCategoryID,omitempty"`
	BusinessSubCategoryName string   `protobuf:"bytes,2,opt,name=businessSubCategoryName,proto3" json:"businessSubCategoryName,omitempty"`
	BusinessCategoryID      int64    `protobuf:"varint,3,opt,name=businessCategoryID,proto3" json:"businessCategoryID,omitempty"`
	XXX_NoUnkeyedLiteral    struct{} `json:"-"`
	XXX_unrecognized        []byte   `json:"-"`
	XXX_sizecache           int32    `json:"-"`
}

func (m *BusinessSubCategory) Reset()         { *m = BusinessSubCategory{} }
func (m *BusinessSubCategory) String() string { return proto.CompactTextString(m) }
func (*BusinessSubCategory) ProtoMessage()    {}
func (*BusinessSubCategory) Descriptor() ([]byte, []int) {
	return fileDescriptor_0abb45d1bdc84429, []int{0}
}

func (m *BusinessSubCategory) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BusinessSubCategory.Unmarshal(m, b)
}
func (m *BusinessSubCategory) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BusinessSubCategory.Marshal(b, m, deterministic)
}
func (m *BusinessSubCategory) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BusinessSubCategory.Merge(m, src)
}
func (m *BusinessSubCategory) XXX_Size() int {
	return xxx_messageInfo_BusinessSubCategory.Size(m)
}
func (m *BusinessSubCategory) XXX_DiscardUnknown() {
	xxx_messageInfo_BusinessSubCategory.DiscardUnknown(m)
}

var xxx_messageInfo_BusinessSubCategory proto.InternalMessageInfo

func (m *BusinessSubCategory) GetBusinessSubCategoryID() int64 {
	if m != nil {
		return m.BusinessSubCategoryID
	}
	return 0
}

func (m *BusinessSubCategory) GetBusinessSubCategoryName() string {
	if m != nil {
		return m.BusinessSubCategoryName
	}
	return ""
}

func (m *BusinessSubCategory) GetBusinessCategoryID() int64 {
	if m != nil {
		return m.BusinessCategoryID
	}
	return 0
}

type BusinessSubCategoryRequest struct {
	BusinessSubCategoryID int64    `protobuf:"varint,1,opt,name=businessSubCategoryID,proto3" json:"businessSubCategoryID,omitempty"`
	XXX_NoUnkeyedLiteral  struct{} `json:"-"`
	XXX_unrecognized      []byte   `json:"-"`
	XXX_sizecache         int32    `json:"-"`
}

func (m *BusinessSubCategoryRequest) Reset()         { *m = BusinessSubCategoryRequest{} }
func (m *BusinessSubCategoryRequest) String() string { return proto.CompactTextString(m) }
func (*BusinessSubCategoryRequest) ProtoMessage()    {}
func (*BusinessSubCategoryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0abb45d1bdc84429, []int{1}
}

func (m *BusinessSubCategoryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BusinessSubCategoryRequest.Unmarshal(m, b)
}
func (m *BusinessSubCategoryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BusinessSubCategoryRequest.Marshal(b, m, deterministic)
}
func (m *BusinessSubCategoryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BusinessSubCategoryRequest.Merge(m, src)
}
func (m *BusinessSubCategoryRequest) XXX_Size() int {
	return xxx_messageInfo_BusinessSubCategoryRequest.Size(m)
}
func (m *BusinessSubCategoryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BusinessSubCategoryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BusinessSubCategoryRequest proto.InternalMessageInfo

func (m *BusinessSubCategoryRequest) GetBusinessSubCategoryID() int64 {
	if m != nil {
		return m.BusinessSubCategoryID
	}
	return 0
}

type BusinessSubCategoriesUnderCategoryRequest struct {
	BusinessCategoryID   int64    `protobuf:"varint,1,opt,name=businessCategoryID,proto3" json:"businessCategoryID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BusinessSubCategoriesUnderCategoryRequest) Reset() {
	*m = BusinessSubCategoriesUnderCategoryRequest{}
}
func (m *BusinessSubCategoriesUnderCategoryRequest) String() string { return proto.CompactTextString(m) }
func (*BusinessSubCategoriesUnderCategoryRequest) ProtoMessage()    {}
func (*BusinessSubCategoriesUnderCategoryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0abb45d1bdc84429, []int{2}
}

func (m *BusinessSubCategoriesUnderCategoryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BusinessSubCategoriesUnderCategoryRequest.Unmarshal(m, b)
}
func (m *BusinessSubCategoriesUnderCategoryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BusinessSubCategoriesUnderCategoryRequest.Marshal(b, m, deterministic)
}
func (m *BusinessSubCategoriesUnderCategoryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BusinessSubCategoriesUnderCategoryRequest.Merge(m, src)
}
func (m *BusinessSubCategoriesUnderCategoryRequest) XXX_Size() int {
	return xxx_messageInfo_BusinessSubCategoriesUnderCategoryRequest.Size(m)
}
func (m *BusinessSubCategoriesUnderCategoryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BusinessSubCategoriesUnderCategoryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BusinessSubCategoriesUnderCategoryRequest proto.InternalMessageInfo

func (m *BusinessSubCategoriesUnderCategoryRequest) GetBusinessCategoryID() int64 {
	if m != nil {
		return m.BusinessCategoryID
	}
	return 0
}

type BusinessSubCategoryResponse struct {
	BusinessSubCategory  *BusinessSubCategory `protobuf:"bytes,1,opt,name=businessSubCategory,proto3" json:"businessSubCategory,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *BusinessSubCategoryResponse) Reset()         { *m = BusinessSubCategoryResponse{} }
func (m *BusinessSubCategoryResponse) String() string { return proto.CompactTextString(m) }
func (*BusinessSubCategoryResponse) ProtoMessage()    {}
func (*BusinessSubCategoryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0abb45d1bdc84429, []int{3}
}

func (m *BusinessSubCategoryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BusinessSubCategoryResponse.Unmarshal(m, b)
}
func (m *BusinessSubCategoryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BusinessSubCategoryResponse.Marshal(b, m, deterministic)
}
func (m *BusinessSubCategoryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BusinessSubCategoryResponse.Merge(m, src)
}
func (m *BusinessSubCategoryResponse) XXX_Size() int {
	return xxx_messageInfo_BusinessSubCategoryResponse.Size(m)
}
func (m *BusinessSubCategoryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BusinessSubCategoryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BusinessSubCategoryResponse proto.InternalMessageInfo

func (m *BusinessSubCategoryResponse) GetBusinessSubCategory() *BusinessSubCategory {
	if m != nil {
		return m.BusinessSubCategory
	}
	return nil
}

type BusinessSubCategoriesResponse struct {
	BusinessSubCategories []*BusinessSubCategory `protobuf:"bytes,1,rep,name=businessSubCategories,proto3" json:"businessSubCategories,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}               `json:"-"`
	XXX_unrecognized      []byte                 `json:"-"`
	XXX_sizecache         int32                  `json:"-"`
}

func (m *BusinessSubCategoriesResponse) Reset()         { *m = BusinessSubCategoriesResponse{} }
func (m *BusinessSubCategoriesResponse) String() string { return proto.CompactTextString(m) }
func (*BusinessSubCategoriesResponse) ProtoMessage()    {}
func (*BusinessSubCategoriesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0abb45d1bdc84429, []int{4}
}

func (m *BusinessSubCategoriesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BusinessSubCategoriesResponse.Unmarshal(m, b)
}
func (m *BusinessSubCategoriesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BusinessSubCategoriesResponse.Marshal(b, m, deterministic)
}
func (m *BusinessSubCategoriesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BusinessSubCategoriesResponse.Merge(m, src)
}
func (m *BusinessSubCategoriesResponse) XXX_Size() int {
	return xxx_messageInfo_BusinessSubCategoriesResponse.Size(m)
}
func (m *BusinessSubCategoriesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BusinessSubCategoriesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BusinessSubCategoriesResponse proto.InternalMessageInfo

func (m *BusinessSubCategoriesResponse) GetBusinessSubCategories() []*BusinessSubCategory {
	if m != nil {
		return m.BusinessSubCategories
	}
	return nil
}

type BusinessSubCategoriesUnderCategoryResponse struct {
	BusinessSubCategories []*BusinessSubCategory `protobuf:"bytes,1,rep,name=businessSubCategories,proto3" json:"businessSubCategories,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}               `json:"-"`
	XXX_unrecognized      []byte                 `json:"-"`
	XXX_sizecache         int32                  `json:"-"`
}

func (m *BusinessSubCategoriesUnderCategoryResponse) Reset() {
	*m = BusinessSubCategoriesUnderCategoryResponse{}
}
func (m *BusinessSubCategoriesUnderCategoryResponse) String() string {
	return proto.CompactTextString(m)
}
func (*BusinessSubCategoriesUnderCategoryResponse) ProtoMessage() {}
func (*BusinessSubCategoriesUnderCategoryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0abb45d1bdc84429, []int{5}
}

func (m *BusinessSubCategoriesUnderCategoryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BusinessSubCategoriesUnderCategoryResponse.Unmarshal(m, b)
}
func (m *BusinessSubCategoriesUnderCategoryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BusinessSubCategoriesUnderCategoryResponse.Marshal(b, m, deterministic)
}
func (m *BusinessSubCategoriesUnderCategoryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BusinessSubCategoriesUnderCategoryResponse.Merge(m, src)
}
func (m *BusinessSubCategoriesUnderCategoryResponse) XXX_Size() int {
	return xxx_messageInfo_BusinessSubCategoriesUnderCategoryResponse.Size(m)
}
func (m *BusinessSubCategoriesUnderCategoryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BusinessSubCategoriesUnderCategoryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BusinessSubCategoriesUnderCategoryResponse proto.InternalMessageInfo

func (m *BusinessSubCategoriesUnderCategoryResponse) GetBusinessSubCategories() []*BusinessSubCategory {
	if m != nil {
		return m.BusinessSubCategories
	}
	return nil
}

func init() {
	proto.RegisterType((*BusinessSubCategory)(nil), "businessSubCategories.BusinessSubCategory")
	proto.RegisterType((*BusinessSubCategoryRequest)(nil), "businessSubCategories.BusinessSubCategoryRequest")
	proto.RegisterType((*BusinessSubCategoriesUnderCategoryRequest)(nil), "businessSubCategories.BusinessSubCategoriesUnderCategoryRequest")
	proto.RegisterType((*BusinessSubCategoryResponse)(nil), "businessSubCategories.BusinessSubCategoryResponse")
	proto.RegisterType((*BusinessSubCategoriesResponse)(nil), "businessSubCategories.BusinessSubCategoriesResponse")
	proto.RegisterType((*BusinessSubCategoriesUnderCategoryResponse)(nil), "businessSubCategories.BusinessSubCategoriesUnderCategoryResponse")
}

func init() { proto.RegisterFile("subCategories.proto", fileDescriptor_0abb45d1bdc84429) }

var fileDescriptor_0abb45d1bdc84429 = []byte{
	// 347 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x94, 0xcf, 0x4a, 0xf3, 0x40,
	0x14, 0xc5, 0x3b, 0x5f, 0xe0, 0x03, 0xaf, 0x88, 0x30, 0xc5, 0x1a, 0x52, 0x84, 0x32, 0x20, 0xd4,
	0x2e, 0xa6, 0x18, 0xbb, 0x70, 0xa9, 0x51, 0x11, 0x37, 0x2e, 0x52, 0xdc, 0xa8, 0x0b, 0x1b, 0xbd,
	0x86, 0x88, 0xcd, 0xc4, 0x4c, 0x22, 0x04, 0x57, 0x7d, 0x01, 0x1f, 0xc5, 0x9d, 0x4b, 0xdf, 0x4d,
	0x4c, 0x88, 0xa4, 0x7a, 0x03, 0x8d, 0x82, 0xeb, 0x93, 0x7b, 0xce, 0x2f, 0xf7, 0xcf, 0x40, 0x5b,
	0xa7, 0xde, 0xc1, 0x24, 0x41, 0x5f, 0xc5, 0x01, 0x6a, 0x19, 0xc5, 0x2a, 0x51, 0x7c, 0xcd, 0x4b,
	0x75, 0x10, 0xa2, 0xd6, 0xe3, 0xaa, 0x68, 0x75, 0x7d, 0xa5, 0xfc, 0x7b, 0x1c, 0xe6, 0x1f, 0x79,
	0xe9, 0xed, 0x10, 0xa7, 0x51, 0x92, 0x15, 0x35, 0xe2, 0x95, 0x41, 0xdb, 0xf9, 0x56, 0x96, 0xf1,
	0x11, 0x10, 0x6e, 0xd9, 0xc9, 0xa1, 0xc9, 0x7a, 0xac, 0x6f, 0xb8, 0xb4, 0xc8, 0x77, 0x61, 0x9d,
	0x10, 0x4e, 0x27, 0x53, 0x34, 0xff, 0xf5, 0x58, 0x7f, 0xc9, 0xad, 0x93, 0xb9, 0x04, 0x5e, 0x4a,
	0x95, 0x30, 0x23, 0x0f, 0x23, 0x14, 0xe1, 0x82, 0x45, 0x60, 0xbb, 0xf8, 0x90, 0xa2, 0x4e, 0x7e,
	0x46, 0x2f, 0x2e, 0x60, 0xcb, 0xa1, 0x3a, 0x78, 0x16, 0xde, 0x60, 0xfc, 0x35, 0x82, 0x06, 0x66,
	0xb5, 0xc0, 0x4f, 0xd0, 0x25, 0x81, 0x75, 0xa4, 0x42, 0x8d, 0xfc, 0x12, 0xda, 0x04, 0x54, 0xee,
	0xb7, 0x6c, 0x0f, 0x24, 0x39, 0x59, 0x49, 0x19, 0x52, 0x36, 0x62, 0xc6, 0x60, 0x83, 0xfc, 0xb5,
	0xcf, 0xfc, 0x2b, 0xa0, 0xb7, 0xc7, 0x64, 0x3d, 0xa3, 0x21, 0x01, 0x6d, 0x24, 0x9e, 0x19, 0x0c,
	0x16, 0x69, 0xef, 0x5f, 0x01, 0xd9, 0x6f, 0x06, 0xb9, 0x43, 0x63, 0x8c, 0x1f, 0x83, 0x6b, 0xe4,
	0x33, 0x06, 0x9d, 0x63, 0x4c, 0xa8, 0xe3, 0xd8, 0x6e, 0x10, 0x5e, 0xac, 0x8b, 0x65, 0x37, 0x29,
	0x29, 0x5a, 0x20, 0x5a, 0xfc, 0x0e, 0x4c, 0x12, 0x21, 0x40, 0xcd, 0x3b, 0xb2, 0xb8, 0x6b, 0x59,
	0xde, 0xb5, 0x3c, 0xfa, 0xb8, 0x6b, 0x6b, 0xb4, 0x70, 0x52, 0x65, 0xfe, 0xa2, 0xc5, 0x5f, 0x18,
	0x6c, 0xd6, 0x85, 0xcd, 0x8d, 0x88, 0xef, 0x35, 0x49, 0xa0, 0x8e, 0xc7, 0xda, 0xff, 0x85, 0x43,
	0x09, 0xec, 0xac, 0x9e, 0xaf, 0xcc, 0xbd, 0x82, 0xde, 0xff, 0xbc, 0x13, 0x3b, 0xef, 0x01, 0x00,
	0x00, 0xff, 0xff, 0x03, 0xd9, 0x04, 0x56, 0x1d, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// BusinessSubCategoryServiceClient is the client API for BusinessSubCategoryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BusinessSubCategoryServiceClient interface {
	GetBusinessSubCategory(ctx context.Context, in *BusinessSubCategoryRequest, opts ...grpc.CallOption) (*BusinessSubCategoryResponse, error)
	GetBusinessSubCategories(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*BusinessSubCategoriesResponse, error)
	GetBusinessSubCategoriesUnderCategory(ctx context.Context, in *BusinessSubCategoriesUnderCategoryRequest, opts ...grpc.CallOption) (*BusinessSubCategoriesUnderCategoryResponse, error)
}

type businessSubCategoryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBusinessSubCategoryServiceClient(cc grpc.ClientConnInterface) BusinessSubCategoryServiceClient {
	return &businessSubCategoryServiceClient{cc}
}

func (c *businessSubCategoryServiceClient) GetBusinessSubCategory(ctx context.Context, in *BusinessSubCategoryRequest, opts ...grpc.CallOption) (*BusinessSubCategoryResponse, error) {
	out := new(BusinessSubCategoryResponse)
	err := c.cc.Invoke(ctx, "/businessSubCategories.BusinessSubCategoryService/GetBusinessSubCategory", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *businessSubCategoryServiceClient) GetBusinessSubCategories(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*BusinessSubCategoriesResponse, error) {
	out := new(BusinessSubCategoriesResponse)
	err := c.cc.Invoke(ctx, "/businessSubCategories.BusinessSubCategoryService/GetBusinessSubCategories", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *businessSubCategoryServiceClient) GetBusinessSubCategoriesUnderCategory(ctx context.Context, in *BusinessSubCategoriesUnderCategoryRequest, opts ...grpc.CallOption) (*BusinessSubCategoriesUnderCategoryResponse, error) {
	out := new(BusinessSubCategoriesUnderCategoryResponse)
	err := c.cc.Invoke(ctx, "/businessSubCategories.BusinessSubCategoryService/GetBusinessSubCategoriesUnderCategory", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BusinessSubCategoryServiceServer is the server API for BusinessSubCategoryService service.
type BusinessSubCategoryServiceServer interface {
	GetBusinessSubCategory(context.Context, *BusinessSubCategoryRequest) (*BusinessSubCategoryResponse, error)
	GetBusinessSubCategories(context.Context, *empty.Empty) (*BusinessSubCategoriesResponse, error)
	GetBusinessSubCategoriesUnderCategory(context.Context, *BusinessSubCategoriesUnderCategoryRequest) (*BusinessSubCategoriesUnderCategoryResponse, error)
}

// UnimplementedBusinessSubCategoryServiceServer can be embedded to have forward compatible implementations.
type UnimplementedBusinessSubCategoryServiceServer struct {
}

func (*UnimplementedBusinessSubCategoryServiceServer) GetBusinessSubCategory(ctx context.Context, req *BusinessSubCategoryRequest) (*BusinessSubCategoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBusinessSubCategory not implemented")
}
func (*UnimplementedBusinessSubCategoryServiceServer) GetBusinessSubCategories(ctx context.Context, req *empty.Empty) (*BusinessSubCategoriesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBusinessSubCategories not implemented")
}
func (*UnimplementedBusinessSubCategoryServiceServer) GetBusinessSubCategoriesUnderCategory(ctx context.Context, req *BusinessSubCategoriesUnderCategoryRequest) (*BusinessSubCategoriesUnderCategoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBusinessSubCategoriesUnderCategory not implemented")
}

func RegisterBusinessSubCategoryServiceServer(s *grpc.Server, srv BusinessSubCategoryServiceServer) {
	s.RegisterService(&_BusinessSubCategoryService_serviceDesc, srv)
}

func _BusinessSubCategoryService_GetBusinessSubCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BusinessSubCategoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BusinessSubCategoryServiceServer).GetBusinessSubCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/businessSubCategories.BusinessSubCategoryService/GetBusinessSubCategory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BusinessSubCategoryServiceServer).GetBusinessSubCategory(ctx, req.(*BusinessSubCategoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BusinessSubCategoryService_GetBusinessSubCategories_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BusinessSubCategoryServiceServer).GetBusinessSubCategories(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/businessSubCategories.BusinessSubCategoryService/GetBusinessSubCategories",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BusinessSubCategoryServiceServer).GetBusinessSubCategories(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _BusinessSubCategoryService_GetBusinessSubCategoriesUnderCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BusinessSubCategoriesUnderCategoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BusinessSubCategoryServiceServer).GetBusinessSubCategoriesUnderCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/businessSubCategories.BusinessSubCategoryService/GetBusinessSubCategoriesUnderCategory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BusinessSubCategoryServiceServer).GetBusinessSubCategoriesUnderCategory(ctx, req.(*BusinessSubCategoriesUnderCategoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _BusinessSubCategoryService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "businessSubCategories.BusinessSubCategoryService",
	HandlerType: (*BusinessSubCategoryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetBusinessSubCategory",
			Handler:    _BusinessSubCategoryService_GetBusinessSubCategory_Handler,
		},
		{
			MethodName: "GetBusinessSubCategories",
			Handler:    _BusinessSubCategoryService_GetBusinessSubCategories_Handler,
		},
		{
			MethodName: "GetBusinessSubCategoriesUnderCategory",
			Handler:    _BusinessSubCategoryService_GetBusinessSubCategoriesUnderCategory_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "subCategories.proto",
}
