// Code generated by protoc-gen-go. DO NOT EDIT.
// source: services.proto

package services

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type BusinessService struct {
	BusinessServiceID    int64    `protobuf:"varint,1,opt,name=businessServiceID,proto3" json:"businessServiceID,omitempty"`
	BusinessServiceName  string   `protobuf:"bytes,2,opt,name=businessServiceName,proto3" json:"businessServiceName,omitempty"`
	SubCategories        []int64  `protobuf:"varint,3,rep,packed,name=subCategories,proto3" json:"subCategories,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BusinessService) Reset()         { *m = BusinessService{} }
func (m *BusinessService) String() string { return proto.CompactTextString(m) }
func (*BusinessService) ProtoMessage()    {}
func (*BusinessService) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e16ccb8c5307b32, []int{0}
}

func (m *BusinessService) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BusinessService.Unmarshal(m, b)
}
func (m *BusinessService) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BusinessService.Marshal(b, m, deterministic)
}
func (m *BusinessService) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BusinessService.Merge(m, src)
}
func (m *BusinessService) XXX_Size() int {
	return xxx_messageInfo_BusinessService.Size(m)
}
func (m *BusinessService) XXX_DiscardUnknown() {
	xxx_messageInfo_BusinessService.DiscardUnknown(m)
}

var xxx_messageInfo_BusinessService proto.InternalMessageInfo

func (m *BusinessService) GetBusinessServiceID() int64 {
	if m != nil {
		return m.BusinessServiceID
	}
	return 0
}

func (m *BusinessService) GetBusinessServiceName() string {
	if m != nil {
		return m.BusinessServiceName
	}
	return ""
}

func (m *BusinessService) GetSubCategories() []int64 {
	if m != nil {
		return m.SubCategories
	}
	return nil
}

type GetBusinessServiceRequest struct {
	BusinessServiceID    int64    `protobuf:"varint,1,opt,name=businessServiceID,proto3" json:"businessServiceID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBusinessServiceRequest) Reset()         { *m = GetBusinessServiceRequest{} }
func (m *GetBusinessServiceRequest) String() string { return proto.CompactTextString(m) }
func (*GetBusinessServiceRequest) ProtoMessage()    {}
func (*GetBusinessServiceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e16ccb8c5307b32, []int{1}
}

func (m *GetBusinessServiceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBusinessServiceRequest.Unmarshal(m, b)
}
func (m *GetBusinessServiceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBusinessServiceRequest.Marshal(b, m, deterministic)
}
func (m *GetBusinessServiceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBusinessServiceRequest.Merge(m, src)
}
func (m *GetBusinessServiceRequest) XXX_Size() int {
	return xxx_messageInfo_GetBusinessServiceRequest.Size(m)
}
func (m *GetBusinessServiceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBusinessServiceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetBusinessServiceRequest proto.InternalMessageInfo

func (m *GetBusinessServiceRequest) GetBusinessServiceID() int64 {
	if m != nil {
		return m.BusinessServiceID
	}
	return 0
}

type GetBusinessServiceResponse struct {
	BusinessService      *BusinessService `protobuf:"bytes,1,opt,name=businessService,proto3" json:"businessService,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *GetBusinessServiceResponse) Reset()         { *m = GetBusinessServiceResponse{} }
func (m *GetBusinessServiceResponse) String() string { return proto.CompactTextString(m) }
func (*GetBusinessServiceResponse) ProtoMessage()    {}
func (*GetBusinessServiceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e16ccb8c5307b32, []int{2}
}

func (m *GetBusinessServiceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBusinessServiceResponse.Unmarshal(m, b)
}
func (m *GetBusinessServiceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBusinessServiceResponse.Marshal(b, m, deterministic)
}
func (m *GetBusinessServiceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBusinessServiceResponse.Merge(m, src)
}
func (m *GetBusinessServiceResponse) XXX_Size() int {
	return xxx_messageInfo_GetBusinessServiceResponse.Size(m)
}
func (m *GetBusinessServiceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBusinessServiceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetBusinessServiceResponse proto.InternalMessageInfo

func (m *GetBusinessServiceResponse) GetBusinessService() *BusinessService {
	if m != nil {
		return m.BusinessService
	}
	return nil
}

type GetBusinessServicesResponse struct {
	BusinessServices     []*BusinessService `protobuf:"bytes,1,rep,name=businessServices,proto3" json:"businessServices,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *GetBusinessServicesResponse) Reset()         { *m = GetBusinessServicesResponse{} }
func (m *GetBusinessServicesResponse) String() string { return proto.CompactTextString(m) }
func (*GetBusinessServicesResponse) ProtoMessage()    {}
func (*GetBusinessServicesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e16ccb8c5307b32, []int{3}
}

func (m *GetBusinessServicesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBusinessServicesResponse.Unmarshal(m, b)
}
func (m *GetBusinessServicesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBusinessServicesResponse.Marshal(b, m, deterministic)
}
func (m *GetBusinessServicesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBusinessServicesResponse.Merge(m, src)
}
func (m *GetBusinessServicesResponse) XXX_Size() int {
	return xxx_messageInfo_GetBusinessServicesResponse.Size(m)
}
func (m *GetBusinessServicesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBusinessServicesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetBusinessServicesResponse proto.InternalMessageInfo

func (m *GetBusinessServicesResponse) GetBusinessServices() []*BusinessService {
	if m != nil {
		return m.BusinessServices
	}
	return nil
}

type CreateBusinessServiceRequest struct {
	BusinessServiceName  string   `protobuf:"bytes,1,opt,name=businessServiceName,proto3" json:"businessServiceName,omitempty"`
	SubCategories        []int64  `protobuf:"varint,2,rep,packed,name=subCategories,proto3" json:"subCategories,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateBusinessServiceRequest) Reset()         { *m = CreateBusinessServiceRequest{} }
func (m *CreateBusinessServiceRequest) String() string { return proto.CompactTextString(m) }
func (*CreateBusinessServiceRequest) ProtoMessage()    {}
func (*CreateBusinessServiceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e16ccb8c5307b32, []int{4}
}

func (m *CreateBusinessServiceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateBusinessServiceRequest.Unmarshal(m, b)
}
func (m *CreateBusinessServiceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateBusinessServiceRequest.Marshal(b, m, deterministic)
}
func (m *CreateBusinessServiceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateBusinessServiceRequest.Merge(m, src)
}
func (m *CreateBusinessServiceRequest) XXX_Size() int {
	return xxx_messageInfo_CreateBusinessServiceRequest.Size(m)
}
func (m *CreateBusinessServiceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateBusinessServiceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateBusinessServiceRequest proto.InternalMessageInfo

func (m *CreateBusinessServiceRequest) GetBusinessServiceName() string {
	if m != nil {
		return m.BusinessServiceName
	}
	return ""
}

func (m *CreateBusinessServiceRequest) GetSubCategories() []int64 {
	if m != nil {
		return m.SubCategories
	}
	return nil
}

type CreateBusinessServiceResponse struct {
	BusinessService      *BusinessService `protobuf:"bytes,1,opt,name=businessService,proto3" json:"businessService,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *CreateBusinessServiceResponse) Reset()         { *m = CreateBusinessServiceResponse{} }
func (m *CreateBusinessServiceResponse) String() string { return proto.CompactTextString(m) }
func (*CreateBusinessServiceResponse) ProtoMessage()    {}
func (*CreateBusinessServiceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e16ccb8c5307b32, []int{5}
}

func (m *CreateBusinessServiceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateBusinessServiceResponse.Unmarshal(m, b)
}
func (m *CreateBusinessServiceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateBusinessServiceResponse.Marshal(b, m, deterministic)
}
func (m *CreateBusinessServiceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateBusinessServiceResponse.Merge(m, src)
}
func (m *CreateBusinessServiceResponse) XXX_Size() int {
	return xxx_messageInfo_CreateBusinessServiceResponse.Size(m)
}
func (m *CreateBusinessServiceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateBusinessServiceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateBusinessServiceResponse proto.InternalMessageInfo

func (m *CreateBusinessServiceResponse) GetBusinessService() *BusinessService {
	if m != nil {
		return m.BusinessService
	}
	return nil
}

type GetServicesUnderSubCategoryRequest struct {
	SubCategoryID        int64    `protobuf:"varint,1,opt,name=SubCategoryID,proto3" json:"SubCategoryID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetServicesUnderSubCategoryRequest) Reset()         { *m = GetServicesUnderSubCategoryRequest{} }
func (m *GetServicesUnderSubCategoryRequest) String() string { return proto.CompactTextString(m) }
func (*GetServicesUnderSubCategoryRequest) ProtoMessage()    {}
func (*GetServicesUnderSubCategoryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e16ccb8c5307b32, []int{6}
}

func (m *GetServicesUnderSubCategoryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetServicesUnderSubCategoryRequest.Unmarshal(m, b)
}
func (m *GetServicesUnderSubCategoryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetServicesUnderSubCategoryRequest.Marshal(b, m, deterministic)
}
func (m *GetServicesUnderSubCategoryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetServicesUnderSubCategoryRequest.Merge(m, src)
}
func (m *GetServicesUnderSubCategoryRequest) XXX_Size() int {
	return xxx_messageInfo_GetServicesUnderSubCategoryRequest.Size(m)
}
func (m *GetServicesUnderSubCategoryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetServicesUnderSubCategoryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetServicesUnderSubCategoryRequest proto.InternalMessageInfo

func (m *GetServicesUnderSubCategoryRequest) GetSubCategoryID() int64 {
	if m != nil {
		return m.SubCategoryID
	}
	return 0
}

type GetServicesUnderSubCategoryResponse struct {
	BusinessServices     []*BusinessService `protobuf:"bytes,1,rep,name=businessServices,proto3" json:"businessServices,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *GetServicesUnderSubCategoryResponse) Reset()         { *m = GetServicesUnderSubCategoryResponse{} }
func (m *GetServicesUnderSubCategoryResponse) String() string { return proto.CompactTextString(m) }
func (*GetServicesUnderSubCategoryResponse) ProtoMessage()    {}
func (*GetServicesUnderSubCategoryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e16ccb8c5307b32, []int{7}
}

func (m *GetServicesUnderSubCategoryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetServicesUnderSubCategoryResponse.Unmarshal(m, b)
}
func (m *GetServicesUnderSubCategoryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetServicesUnderSubCategoryResponse.Marshal(b, m, deterministic)
}
func (m *GetServicesUnderSubCategoryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetServicesUnderSubCategoryResponse.Merge(m, src)
}
func (m *GetServicesUnderSubCategoryResponse) XXX_Size() int {
	return xxx_messageInfo_GetServicesUnderSubCategoryResponse.Size(m)
}
func (m *GetServicesUnderSubCategoryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetServicesUnderSubCategoryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetServicesUnderSubCategoryResponse proto.InternalMessageInfo

func (m *GetServicesUnderSubCategoryResponse) GetBusinessServices() []*BusinessService {
	if m != nil {
		return m.BusinessServices
	}
	return nil
}

func init() {
	proto.RegisterType((*BusinessService)(nil), "businessServices.BusinessService")
	proto.RegisterType((*GetBusinessServiceRequest)(nil), "businessServices.GetBusinessServiceRequest")
	proto.RegisterType((*GetBusinessServiceResponse)(nil), "businessServices.GetBusinessServiceResponse")
	proto.RegisterType((*GetBusinessServicesResponse)(nil), "businessServices.GetBusinessServicesResponse")
	proto.RegisterType((*CreateBusinessServiceRequest)(nil), "businessServices.CreateBusinessServiceRequest")
	proto.RegisterType((*CreateBusinessServiceResponse)(nil), "businessServices.CreateBusinessServiceResponse")
	proto.RegisterType((*GetServicesUnderSubCategoryRequest)(nil), "businessServices.GetServicesUnderSubCategoryRequest")
	proto.RegisterType((*GetServicesUnderSubCategoryResponse)(nil), "businessServices.GetServicesUnderSubCategoryResponse")
}

func init() { proto.RegisterFile("services.proto", fileDescriptor_8e16ccb8c5307b32) }

var fileDescriptor_8e16ccb8c5307b32 = []byte{
	// 392 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x54, 0xcd, 0x4e, 0xea, 0x40,
	0x14, 0xbe, 0xa5, 0xc9, 0xcd, 0xbd, 0xc7, 0x20, 0x38, 0x44, 0x53, 0x8b, 0x26, 0x75, 0x64, 0x41,
	0x22, 0x0e, 0x06, 0xf5, 0x05, 0x40, 0x43, 0xd0, 0xe8, 0xa2, 0xc4, 0x8d, 0x0b, 0x13, 0xaa, 0x47,
	0xd2, 0x04, 0x28, 0x74, 0xa6, 0x24, 0xf8, 0x0c, 0xee, 0x7d, 0x4d, 0x1f, 0xc1, 0x58, 0x6c, 0x03,
	0x33, 0x2d, 0x96, 0x05, 0xdb, 0xf3, 0xf3, 0x9d, 0x33, 0xdf, 0xf7, 0xcd, 0x81, 0x6d, 0x8e, 0xfe,
	0xd4, 0x7d, 0x46, 0xce, 0xc6, 0xbe, 0x27, 0x3c, 0x52, 0x74, 0x02, 0xee, 0x8e, 0x90, 0xf3, 0xee,
	0x4f, 0xdc, 0x2c, 0xf7, 0x3d, 0xaf, 0x3f, 0xc0, 0x7a, 0x98, 0x77, 0x82, 0xd7, 0x3a, 0x0e, 0xc7,
	0x62, 0x36, 0x2f, 0xa7, 0x1f, 0x1a, 0x14, 0x9a, 0xcb, 0x1d, 0xa4, 0x06, 0x3b, 0x12, 0x48, 0xe7,
	0xca, 0xd0, 0x2c, 0xad, 0xaa, 0xdb, 0x6a, 0x82, 0x9c, 0x41, 0x49, 0x0a, 0xde, 0xf7, 0x86, 0x68,
	0xe4, 0x2c, 0xad, 0xfa, 0xdf, 0x4e, 0x4a, 0x91, 0x0a, 0xe4, 0x79, 0xe0, 0xb4, 0x7a, 0x02, 0xfb,
	0x9e, 0xef, 0x22, 0x37, 0x74, 0x4b, 0xaf, 0xea, 0xf6, 0x72, 0x90, 0x76, 0x60, 0xbf, 0x8d, 0x42,
	0xda, 0xcd, 0xc6, 0x49, 0x80, 0x5c, 0xac, 0xb7, 0x22, 0x75, 0xc1, 0x4c, 0x82, 0xe2, 0x63, 0x6f,
	0xc4, 0x91, 0xdc, 0x42, 0x41, 0x6a, 0x09, 0x91, 0xb6, 0x1a, 0x47, 0x4c, 0xe6, 0x92, 0xc9, 0x18,
	0x72, 0x27, 0x1d, 0x40, 0x59, 0x1d, 0xc5, 0xe3, 0x59, 0x77, 0xa0, 0xe8, 0x63, 0x68, 0x96, 0x9e,
	0x6d, 0x98, 0xd2, 0x4a, 0xa7, 0x70, 0xd0, 0xf2, 0xb1, 0x27, 0x30, 0x85, 0xa6, 0x14, 0x6d, 0xb4,
	0x35, 0xb4, 0xc9, 0x25, 0x69, 0x33, 0x80, 0xc3, 0x94, 0xb9, 0x9b, 0xe0, 0xf4, 0x06, 0x68, 0x1b,
	0x45, 0x54, 0xff, 0x30, 0x7a, 0x41, 0xbf, 0x1b, 0xaf, 0x33, 0x8b, 0xde, 0x5a, 0x81, 0xfc, 0x42,
	0x34, 0xb6, 0xc3, 0x72, 0x90, 0x0a, 0x38, 0x5e, 0x89, 0xb5, 0x11, 0x9d, 0x1a, 0x9f, 0x3a, 0x14,
	0x65, 0x4f, 0x90, 0x09, 0x10, 0xd5, 0x2a, 0xe4, 0x44, 0xc5, 0x4f, 0xfd, 0x06, 0x66, 0x2d, 0x5b,
	0xf1, 0xfc, 0x51, 0xf4, 0x0f, 0x79, 0x82, 0x52, 0x82, 0x3b, 0xc9, 0x1e, 0x9b, 0x9f, 0x08, 0x16,
	0x9d, 0x08, 0x76, 0xfd, 0x7d, 0x22, 0xcc, 0xd3, 0x2c, 0xf0, 0x7c, 0x01, 0xff, 0x5d, 0x0b, 0xed,
	0x9f, 0x46, 0x2f, 0xb9, 0x48, 0x04, 0xfc, 0x45, 0x59, 0xf3, 0x72, 0xcd, 0xae, 0x78, 0x9d, 0x37,
	0xd8, 0x4d, 0xb4, 0x29, 0x61, 0x2a, 0xe2, 0xaa, 0x7f, 0x64, 0xd6, 0x33, 0xd7, 0x47, 0xb3, 0x9b,
	0xf0, 0xf8, 0x2f, 0xba, 0xcc, 0xce, 0xdf, 0x90, 0xd7, 0xf3, 0xaf, 0x00, 0x00, 0x00, 0xff, 0xff,
	0xd3, 0x12, 0xbb, 0xc0, 0xac, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// BusinessServicesClient is the client API for BusinessServices service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BusinessServicesClient interface {
	GetBusinessService(ctx context.Context, in *GetBusinessServiceRequest, opts ...grpc.CallOption) (*GetBusinessServiceResponse, error)
	GetBusinessServices(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*GetBusinessServicesResponse, error)
	GetServicesUnderSubCategory(ctx context.Context, in *GetServicesUnderSubCategoryRequest, opts ...grpc.CallOption) (*GetServicesUnderSubCategoryResponse, error)
	CreateBusinessService(ctx context.Context, in *CreateBusinessServiceRequest, opts ...grpc.CallOption) (*CreateBusinessServiceResponse, error)
}

type businessServicesClient struct {
	cc grpc.ClientConnInterface
}

func NewBusinessServicesClient(cc grpc.ClientConnInterface) BusinessServicesClient {
	return &businessServicesClient{cc}
}

func (c *businessServicesClient) GetBusinessService(ctx context.Context, in *GetBusinessServiceRequest, opts ...grpc.CallOption) (*GetBusinessServiceResponse, error) {
	out := new(GetBusinessServiceResponse)
	err := c.cc.Invoke(ctx, "/businessServices.BusinessServices/GetBusinessService", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *businessServicesClient) GetBusinessServices(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*GetBusinessServicesResponse, error) {
	out := new(GetBusinessServicesResponse)
	err := c.cc.Invoke(ctx, "/businessServices.BusinessServices/GetBusinessServices", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *businessServicesClient) GetServicesUnderSubCategory(ctx context.Context, in *GetServicesUnderSubCategoryRequest, opts ...grpc.CallOption) (*GetServicesUnderSubCategoryResponse, error) {
	out := new(GetServicesUnderSubCategoryResponse)
	err := c.cc.Invoke(ctx, "/businessServices.BusinessServices/GetServicesUnderSubCategory", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *businessServicesClient) CreateBusinessService(ctx context.Context, in *CreateBusinessServiceRequest, opts ...grpc.CallOption) (*CreateBusinessServiceResponse, error) {
	out := new(CreateBusinessServiceResponse)
	err := c.cc.Invoke(ctx, "/businessServices.BusinessServices/CreateBusinessService", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BusinessServicesServer is the server API for BusinessServices service.
type BusinessServicesServer interface {
	GetBusinessService(context.Context, *GetBusinessServiceRequest) (*GetBusinessServiceResponse, error)
	GetBusinessServices(context.Context, *empty.Empty) (*GetBusinessServicesResponse, error)
	GetServicesUnderSubCategory(context.Context, *GetServicesUnderSubCategoryRequest) (*GetServicesUnderSubCategoryResponse, error)
	CreateBusinessService(context.Context, *CreateBusinessServiceRequest) (*CreateBusinessServiceResponse, error)
}

// UnimplementedBusinessServicesServer can be embedded to have forward compatible implementations.
type UnimplementedBusinessServicesServer struct {
}

func (*UnimplementedBusinessServicesServer) GetBusinessService(ctx context.Context, req *GetBusinessServiceRequest) (*GetBusinessServiceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBusinessService not implemented")
}
func (*UnimplementedBusinessServicesServer) GetBusinessServices(ctx context.Context, req *empty.Empty) (*GetBusinessServicesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBusinessServices not implemented")
}
func (*UnimplementedBusinessServicesServer) GetServicesUnderSubCategory(ctx context.Context, req *GetServicesUnderSubCategoryRequest) (*GetServicesUnderSubCategoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetServicesUnderSubCategory not implemented")
}
func (*UnimplementedBusinessServicesServer) CreateBusinessService(ctx context.Context, req *CreateBusinessServiceRequest) (*CreateBusinessServiceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateBusinessService not implemented")
}

func RegisterBusinessServicesServer(s *grpc.Server, srv BusinessServicesServer) {
	s.RegisterService(&_BusinessServices_serviceDesc, srv)
}

func _BusinessServices_GetBusinessService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBusinessServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BusinessServicesServer).GetBusinessService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/businessServices.BusinessServices/GetBusinessService",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BusinessServicesServer).GetBusinessService(ctx, req.(*GetBusinessServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BusinessServices_GetBusinessServices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BusinessServicesServer).GetBusinessServices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/businessServices.BusinessServices/GetBusinessServices",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BusinessServicesServer).GetBusinessServices(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _BusinessServices_GetServicesUnderSubCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetServicesUnderSubCategoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BusinessServicesServer).GetServicesUnderSubCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/businessServices.BusinessServices/GetServicesUnderSubCategory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BusinessServicesServer).GetServicesUnderSubCategory(ctx, req.(*GetServicesUnderSubCategoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BusinessServices_CreateBusinessService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBusinessServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BusinessServicesServer).CreateBusinessService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/businessServices.BusinessServices/CreateBusinessService",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BusinessServicesServer).CreateBusinessService(ctx, req.(*CreateBusinessServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _BusinessServices_serviceDesc = grpc.ServiceDesc{
	ServiceName: "businessServices.BusinessServices",
	HandlerType: (*BusinessServicesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetBusinessService",
			Handler:    _BusinessServices_GetBusinessService_Handler,
		},
		{
			MethodName: "GetBusinessServices",
			Handler:    _BusinessServices_GetBusinessServices_Handler,
		},
		{
			MethodName: "GetServicesUnderSubCategory",
			Handler:    _BusinessServices_GetServicesUnderSubCategory_Handler,
		},
		{
			MethodName: "CreateBusinessService",
			Handler:    _BusinessServices_CreateBusinessService_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "services.proto",
}
