// Code generated by protoc-gen-go. DO NOT EDIT.
// source: categories/categories.proto

package categories

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type BusinessCategory struct {
	BusinessCategoryID   int64    `protobuf:"varint,1,opt,name=businessCategoryID,proto3" json:"businessCategoryID,omitempty"`
	BusinessCategoryName string   `protobuf:"bytes,2,opt,name=businessCategoryName,proto3" json:"businessCategoryName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BusinessCategory) Reset()         { *m = BusinessCategory{} }
func (m *BusinessCategory) String() string { return proto.CompactTextString(m) }
func (*BusinessCategory) ProtoMessage()    {}
func (*BusinessCategory) Descriptor() ([]byte, []int) {
	return fileDescriptor_a600a40d11b35390, []int{0}
}

func (m *BusinessCategory) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BusinessCategory.Unmarshal(m, b)
}
func (m *BusinessCategory) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BusinessCategory.Marshal(b, m, deterministic)
}
func (m *BusinessCategory) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BusinessCategory.Merge(m, src)
}
func (m *BusinessCategory) XXX_Size() int {
	return xxx_messageInfo_BusinessCategory.Size(m)
}
func (m *BusinessCategory) XXX_DiscardUnknown() {
	xxx_messageInfo_BusinessCategory.DiscardUnknown(m)
}

var xxx_messageInfo_BusinessCategory proto.InternalMessageInfo

func (m *BusinessCategory) GetBusinessCategoryID() int64 {
	if m != nil {
		return m.BusinessCategoryID
	}
	return 0
}

func (m *BusinessCategory) GetBusinessCategoryName() string {
	if m != nil {
		return m.BusinessCategoryName
	}
	return ""
}

type BusinessCategoryRequest struct {
	BusinessCategoryID   int64    `protobuf:"varint,1,opt,name=BusinessCategoryID,proto3" json:"BusinessCategoryID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BusinessCategoryRequest) Reset()         { *m = BusinessCategoryRequest{} }
func (m *BusinessCategoryRequest) String() string { return proto.CompactTextString(m) }
func (*BusinessCategoryRequest) ProtoMessage()    {}
func (*BusinessCategoryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a600a40d11b35390, []int{1}
}

func (m *BusinessCategoryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BusinessCategoryRequest.Unmarshal(m, b)
}
func (m *BusinessCategoryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BusinessCategoryRequest.Marshal(b, m, deterministic)
}
func (m *BusinessCategoryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BusinessCategoryRequest.Merge(m, src)
}
func (m *BusinessCategoryRequest) XXX_Size() int {
	return xxx_messageInfo_BusinessCategoryRequest.Size(m)
}
func (m *BusinessCategoryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BusinessCategoryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BusinessCategoryRequest proto.InternalMessageInfo

func (m *BusinessCategoryRequest) GetBusinessCategoryID() int64 {
	if m != nil {
		return m.BusinessCategoryID
	}
	return 0
}

type BusinessCategoryResponse struct {
	BusinessCategory     *BusinessCategory `protobuf:"bytes,1,opt,name=BusinessCategory,proto3" json:"BusinessCategory,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *BusinessCategoryResponse) Reset()         { *m = BusinessCategoryResponse{} }
func (m *BusinessCategoryResponse) String() string { return proto.CompactTextString(m) }
func (*BusinessCategoryResponse) ProtoMessage()    {}
func (*BusinessCategoryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a600a40d11b35390, []int{2}
}

func (m *BusinessCategoryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BusinessCategoryResponse.Unmarshal(m, b)
}
func (m *BusinessCategoryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BusinessCategoryResponse.Marshal(b, m, deterministic)
}
func (m *BusinessCategoryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BusinessCategoryResponse.Merge(m, src)
}
func (m *BusinessCategoryResponse) XXX_Size() int {
	return xxx_messageInfo_BusinessCategoryResponse.Size(m)
}
func (m *BusinessCategoryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BusinessCategoryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BusinessCategoryResponse proto.InternalMessageInfo

func (m *BusinessCategoryResponse) GetBusinessCategory() *BusinessCategory {
	if m != nil {
		return m.BusinessCategory
	}
	return nil
}

type BusinessCategoriesResponse struct {
	BusinessCategories   []*BusinessCategory `protobuf:"bytes,1,rep,name=businessCategories,proto3" json:"businessCategories,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *BusinessCategoriesResponse) Reset()         { *m = BusinessCategoriesResponse{} }
func (m *BusinessCategoriesResponse) String() string { return proto.CompactTextString(m) }
func (*BusinessCategoriesResponse) ProtoMessage()    {}
func (*BusinessCategoriesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a600a40d11b35390, []int{3}
}

func (m *BusinessCategoriesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BusinessCategoriesResponse.Unmarshal(m, b)
}
func (m *BusinessCategoriesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BusinessCategoriesResponse.Marshal(b, m, deterministic)
}
func (m *BusinessCategoriesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BusinessCategoriesResponse.Merge(m, src)
}
func (m *BusinessCategoriesResponse) XXX_Size() int {
	return xxx_messageInfo_BusinessCategoriesResponse.Size(m)
}
func (m *BusinessCategoriesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BusinessCategoriesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BusinessCategoriesResponse proto.InternalMessageInfo

func (m *BusinessCategoriesResponse) GetBusinessCategories() []*BusinessCategory {
	if m != nil {
		return m.BusinessCategories
	}
	return nil
}

func init() {
	proto.RegisterType((*BusinessCategory)(nil), "businessCategories.BusinessCategory")
	proto.RegisterType((*BusinessCategoryRequest)(nil), "businessCategories.BusinessCategoryRequest")
	proto.RegisterType((*BusinessCategoryResponse)(nil), "businessCategories.BusinessCategoryResponse")
	proto.RegisterType((*BusinessCategoriesResponse)(nil), "businessCategories.BusinessCategoriesResponse")
}

func init() { proto.RegisterFile("categories/categories.proto", fileDescriptor_a600a40d11b35390) }

var fileDescriptor_a600a40d11b35390 = []byte{
	// 276 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0x4f, 0x4b, 0xc3, 0x40,
	0x14, 0xc4, 0xbb, 0x16, 0x04, 0x9f, 0x1e, 0x64, 0xfd, 0x17, 0xd2, 0x4b, 0x58, 0x3c, 0x14, 0x94,
	0x0d, 0xc4, 0x6f, 0x10, 0x15, 0xe9, 0x45, 0x24, 0x7a, 0xf2, 0x96, 0x94, 0x67, 0x08, 0xb4, 0xdd,
	0xb8, 0x6f, 0x53, 0xc8, 0xb7, 0xf6, 0x23, 0x48, 0x13, 0x6c, 0x34, 0x2f, 0x42, 0x6e, 0x21, 0xb3,
	0x33, 0x3f, 0x76, 0x76, 0x60, 0xb6, 0x4c, 0x1d, 0xe6, 0xc6, 0x16, 0x48, 0x61, 0xf7, 0xa9, 0x4b,
	0x6b, 0x9c, 0x91, 0x32, 0xab, 0xa8, 0xd8, 0x20, 0xd1, 0xfd, 0x5e, 0xf1, 0x67, 0xb9, 0x31, 0xf9,
	0x0a, 0xc3, 0xe6, 0x44, 0x56, 0x7d, 0x84, 0xb8, 0x2e, 0x5d, 0xdd, 0x1a, 0xd4, 0x16, 0x4e, 0xe3,
	0xbf, 0x96, 0x5a, 0x6a, 0xe8, 0xc7, 0xd4, 0x8b, 0x07, 0x4f, 0x04, 0x62, 0x3e, 0x4d, 0x06, 0x14,
	0x19, 0xc1, 0x79, 0xff, 0xef, 0x73, 0xba, 0x46, 0xef, 0x20, 0x10, 0xf3, 0xa3, 0x64, 0x50, 0x53,
	0x0b, 0xb8, 0xea, 0x73, 0x13, 0xfc, 0xac, 0x90, 0xdc, 0x0e, 0x1f, 0xff, 0x8b, 0xe7, 0x8a, 0x5a,
	0x81, 0xc7, 0xa3, 0xa8, 0x34, 0x1b, 0x42, 0xf9, 0xc2, 0xaf, 0xd7, 0x24, 0x1d, 0x47, 0xd7, 0x9a,
	0x57, 0xa5, 0x59, 0x0e, 0x73, 0x2b, 0x0b, 0x7e, 0xcc, 0x8c, 0x7b, 0xde, 0x1b, 0x0c, 0xbc, 0x80,
	0x27, 0x82, 0xe9, 0x68, 0xe2, 0x80, 0x3f, 0xfa, 0x12, 0xbc, 0xad, 0x57, 0xb4, 0xdb, 0x62, 0x89,
	0xd2, 0xc2, 0xd9, 0x13, 0x3a, 0xf6, 0x86, 0x37, 0xa3, 0x60, 0x6d, 0xe3, 0xfe, 0xed, 0xb8, 0xc3,
	0xed, 0x1d, 0xd5, 0x44, 0xa6, 0x70, 0xc1, 0x99, 0x05, 0x92, 0xbc, 0xd4, 0xed, 0xd6, 0xf4, 0xcf,
	0xd6, 0xf4, 0xe3, 0x6e, 0x6b, 0xbe, 0x1e, 0x01, 0xf8, 0x55, 0xa3, 0x9a, 0xc4, 0x27, 0xef, 0xd0,
	0x8d, 0x3b, 0x3b, 0x6c, 0xf2, 0xee, 0xbe, 0x03, 0x00, 0x00, 0xff, 0xff, 0x1c, 0xb1, 0xb9, 0xcd,
	0xfc, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// BusinessCategoryServiceClient is the client API for BusinessCategoryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BusinessCategoryServiceClient interface {
	GetBusinessCategory(ctx context.Context, in *BusinessCategoryRequest, opts ...grpc.CallOption) (*BusinessCategoryResponse, error)
	GetBusinessCategories(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*BusinessCategoriesResponse, error)
}

type businessCategoryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBusinessCategoryServiceClient(cc grpc.ClientConnInterface) BusinessCategoryServiceClient {
	return &businessCategoryServiceClient{cc}
}

func (c *businessCategoryServiceClient) GetBusinessCategory(ctx context.Context, in *BusinessCategoryRequest, opts ...grpc.CallOption) (*BusinessCategoryResponse, error) {
	out := new(BusinessCategoryResponse)
	err := c.cc.Invoke(ctx, "/businessCategories.BusinessCategoryService/GetBusinessCategory", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *businessCategoryServiceClient) GetBusinessCategories(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*BusinessCategoriesResponse, error) {
	out := new(BusinessCategoriesResponse)
	err := c.cc.Invoke(ctx, "/businessCategories.BusinessCategoryService/GetBusinessCategories", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BusinessCategoryServiceServer is the server API for BusinessCategoryService service.
type BusinessCategoryServiceServer interface {
	GetBusinessCategory(context.Context, *BusinessCategoryRequest) (*BusinessCategoryResponse, error)
	GetBusinessCategories(context.Context, *empty.Empty) (*BusinessCategoriesResponse, error)
}

// UnimplementedBusinessCategoryServiceServer can be embedded to have forward compatible implementations.
type UnimplementedBusinessCategoryServiceServer struct {
}

func (*UnimplementedBusinessCategoryServiceServer) GetBusinessCategory(ctx context.Context, req *BusinessCategoryRequest) (*BusinessCategoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBusinessCategory not implemented")
}
func (*UnimplementedBusinessCategoryServiceServer) GetBusinessCategories(ctx context.Context, req *empty.Empty) (*BusinessCategoriesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBusinessCategories not implemented")
}

func RegisterBusinessCategoryServiceServer(s *grpc.Server, srv BusinessCategoryServiceServer) {
	s.RegisterService(&_BusinessCategoryService_serviceDesc, srv)
}

func _BusinessCategoryService_GetBusinessCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BusinessCategoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BusinessCategoryServiceServer).GetBusinessCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/businessCategories.BusinessCategoryService/GetBusinessCategory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BusinessCategoryServiceServer).GetBusinessCategory(ctx, req.(*BusinessCategoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BusinessCategoryService_GetBusinessCategories_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BusinessCategoryServiceServer).GetBusinessCategories(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/businessCategories.BusinessCategoryService/GetBusinessCategories",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BusinessCategoryServiceServer).GetBusinessCategories(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _BusinessCategoryService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "businessCategories.BusinessCategoryService",
	HandlerType: (*BusinessCategoryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetBusinessCategory",
			Handler:    _BusinessCategoryService_GetBusinessCategory_Handler,
		},
		{
			MethodName: "GetBusinessCategories",
			Handler:    _BusinessCategoryService_GetBusinessCategories_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "categories/categories.proto",
}
