// Code generated by protoc-gen-go. DO NOT EDIT.
// source: companies.proto

package companies

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type BusinessCompany struct {
	BusinessCompanyID         int64    `protobuf:"varint,1,opt,name=businessCompanyID,proto3" json:"businessCompanyID,omitempty"`
	BusinessCompanyName       string   `protobuf:"bytes,2,opt,name=businessCompanyName,proto3" json:"businessCompanyName,omitempty"`
	BusinessCompanyCategoryID int64    `protobuf:"varint,3,opt,name=businessCompanyCategoryID,proto3" json:"businessCompanyCategoryID,omitempty"`
	XXX_NoUnkeyedLiteral      struct{} `json:"-"`
	XXX_unrecognized          []byte   `json:"-"`
	XXX_sizecache             int32    `json:"-"`
}

func (m *BusinessCompany) Reset()         { *m = BusinessCompany{} }
func (m *BusinessCompany) String() string { return proto.CompactTextString(m) }
func (*BusinessCompany) ProtoMessage()    {}
func (*BusinessCompany) Descriptor() ([]byte, []int) {
	return fileDescriptor_42797fc8bb925a7c, []int{0}
}

func (m *BusinessCompany) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BusinessCompany.Unmarshal(m, b)
}
func (m *BusinessCompany) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BusinessCompany.Marshal(b, m, deterministic)
}
func (m *BusinessCompany) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BusinessCompany.Merge(m, src)
}
func (m *BusinessCompany) XXX_Size() int {
	return xxx_messageInfo_BusinessCompany.Size(m)
}
func (m *BusinessCompany) XXX_DiscardUnknown() {
	xxx_messageInfo_BusinessCompany.DiscardUnknown(m)
}

var xxx_messageInfo_BusinessCompany proto.InternalMessageInfo

func (m *BusinessCompany) GetBusinessCompanyID() int64 {
	if m != nil {
		return m.BusinessCompanyID
	}
	return 0
}

func (m *BusinessCompany) GetBusinessCompanyName() string {
	if m != nil {
		return m.BusinessCompanyName
	}
	return ""
}

func (m *BusinessCompany) GetBusinessCompanyCategoryID() int64 {
	if m != nil {
		return m.BusinessCompanyCategoryID
	}
	return 0
}

type CreateBusinessCompanyRequest struct {
	BusinessCompanyName       string   `protobuf:"bytes,1,opt,name=businessCompanyName,proto3" json:"businessCompanyName,omitempty"`
	BusinessCompanyCategoryID int64    `protobuf:"varint,2,opt,name=businessCompanyCategoryID,proto3" json:"businessCompanyCategoryID,omitempty"`
	XXX_NoUnkeyedLiteral      struct{} `json:"-"`
	XXX_unrecognized          []byte   `json:"-"`
	XXX_sizecache             int32    `json:"-"`
}

func (m *CreateBusinessCompanyRequest) Reset()         { *m = CreateBusinessCompanyRequest{} }
func (m *CreateBusinessCompanyRequest) String() string { return proto.CompactTextString(m) }
func (*CreateBusinessCompanyRequest) ProtoMessage()    {}
func (*CreateBusinessCompanyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_42797fc8bb925a7c, []int{1}
}

func (m *CreateBusinessCompanyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateBusinessCompanyRequest.Unmarshal(m, b)
}
func (m *CreateBusinessCompanyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateBusinessCompanyRequest.Marshal(b, m, deterministic)
}
func (m *CreateBusinessCompanyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateBusinessCompanyRequest.Merge(m, src)
}
func (m *CreateBusinessCompanyRequest) XXX_Size() int {
	return xxx_messageInfo_CreateBusinessCompanyRequest.Size(m)
}
func (m *CreateBusinessCompanyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateBusinessCompanyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateBusinessCompanyRequest proto.InternalMessageInfo

func (m *CreateBusinessCompanyRequest) GetBusinessCompanyName() string {
	if m != nil {
		return m.BusinessCompanyName
	}
	return ""
}

func (m *CreateBusinessCompanyRequest) GetBusinessCompanyCategoryID() int64 {
	if m != nil {
		return m.BusinessCompanyCategoryID
	}
	return 0
}

type CreateBusinessCompanyResponse struct {
	BusinessCompany      *BusinessCompany `protobuf:"bytes,1,opt,name=BusinessCompany,proto3" json:"BusinessCompany,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *CreateBusinessCompanyResponse) Reset()         { *m = CreateBusinessCompanyResponse{} }
func (m *CreateBusinessCompanyResponse) String() string { return proto.CompactTextString(m) }
func (*CreateBusinessCompanyResponse) ProtoMessage()    {}
func (*CreateBusinessCompanyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_42797fc8bb925a7c, []int{2}
}

func (m *CreateBusinessCompanyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateBusinessCompanyResponse.Unmarshal(m, b)
}
func (m *CreateBusinessCompanyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateBusinessCompanyResponse.Marshal(b, m, deterministic)
}
func (m *CreateBusinessCompanyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateBusinessCompanyResponse.Merge(m, src)
}
func (m *CreateBusinessCompanyResponse) XXX_Size() int {
	return xxx_messageInfo_CreateBusinessCompanyResponse.Size(m)
}
func (m *CreateBusinessCompanyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateBusinessCompanyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateBusinessCompanyResponse proto.InternalMessageInfo

func (m *CreateBusinessCompanyResponse) GetBusinessCompany() *BusinessCompany {
	if m != nil {
		return m.BusinessCompany
	}
	return nil
}

func init() {
	proto.RegisterType((*BusinessCompany)(nil), "businessCompanies.BusinessCompany")
	proto.RegisterType((*CreateBusinessCompanyRequest)(nil), "businessCompanies.CreateBusinessCompanyRequest")
	proto.RegisterType((*CreateBusinessCompanyResponse)(nil), "businessCompanies.CreateBusinessCompanyResponse")
}

func init() { proto.RegisterFile("companies.proto", fileDescriptor_42797fc8bb925a7c) }

var fileDescriptor_42797fc8bb925a7c = []byte{
	// 229 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4f, 0xce, 0xcf, 0x2d,
	0x48, 0xcc, 0xcb, 0x4c, 0x2d, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x12, 0x4c, 0x2a, 0x2d,
	0xce, 0xcc, 0x4b, 0x2d, 0x2e, 0x76, 0x86, 0x49, 0x28, 0xad, 0x67, 0xe4, 0xe2, 0x77, 0x42, 0x11,
	0xad, 0x14, 0xd2, 0xe1, 0x42, 0x53, 0x58, 0xe9, 0xe9, 0x22, 0xc1, 0xa8, 0xc0, 0xa8, 0xc1, 0x1c,
	0x84, 0x29, 0x21, 0x64, 0xc0, 0x25, 0x8c, 0x26, 0xe8, 0x97, 0x98, 0x9b, 0x2a, 0xc1, 0xa4, 0xc0,
	0xa8, 0xc1, 0x19, 0x84, 0x4d, 0x4a, 0xc8, 0x86, 0x4b, 0x12, 0x4d, 0xd8, 0x39, 0xb1, 0x24, 0x35,
	0x3d, 0xbf, 0x08, 0x64, 0x0f, 0x33, 0xd8, 0x1e, 0xdc, 0x0a, 0x94, 0xfa, 0x18, 0xb9, 0x64, 0x9c,
	0x8b, 0x52, 0x13, 0x4b, 0x52, 0xd1, 0xdc, 0x1d, 0x94, 0x5a, 0x58, 0x9a, 0x5a, 0x5c, 0x82, 0xcb,
	0x41, 0x8c, 0x64, 0x3a, 0x88, 0x89, 0x90, 0x83, 0x72, 0xb9, 0x64, 0x71, 0xb8, 0xa7, 0xb8, 0x20,
	0x3f, 0xaf, 0x38, 0x55, 0xc8, 0x07, 0x23, 0x88, 0xc1, 0x8e, 0xe1, 0x36, 0x52, 0xd2, 0xc3, 0x88,
	0x10, 0x3d, 0x74, 0x43, 0xd0, 0xb5, 0x1a, 0xcd, 0x60, 0xe4, 0x92, 0x70, 0x42, 0xd7, 0x16, 0x9c,
	0x5a, 0x54, 0x96, 0x99, 0x9c, 0x2a, 0x54, 0xc3, 0x25, 0x8a, 0xd5, 0x2d, 0x42, 0xfa, 0x58, 0xac,
	0xc2, 0x17, 0x8a, 0x52, 0x06, 0xc4, 0x6b, 0x80, 0x78, 0x53, 0x89, 0xc1, 0x89, 0x3b, 0x8a, 0x13,
	0x9e, 0xe4, 0x92, 0xd8, 0xc0, 0x69, 0xce, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0x70, 0x20, 0xb5,
	0xd9, 0x86, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// BusinessCompaniesServiceClient is the client API for BusinessCompaniesService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BusinessCompaniesServiceClient interface {
	CreateBusinessCompany(ctx context.Context, in *CreateBusinessCompanyRequest, opts ...grpc.CallOption) (*CreateBusinessCompanyResponse, error)
}

type businessCompaniesServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBusinessCompaniesServiceClient(cc grpc.ClientConnInterface) BusinessCompaniesServiceClient {
	return &businessCompaniesServiceClient{cc}
}

func (c *businessCompaniesServiceClient) CreateBusinessCompany(ctx context.Context, in *CreateBusinessCompanyRequest, opts ...grpc.CallOption) (*CreateBusinessCompanyResponse, error) {
	out := new(CreateBusinessCompanyResponse)
	err := c.cc.Invoke(ctx, "/businessCompanies.BusinessCompaniesService/CreateBusinessCompany", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BusinessCompaniesServiceServer is the server API for BusinessCompaniesService service.
type BusinessCompaniesServiceServer interface {
	CreateBusinessCompany(context.Context, *CreateBusinessCompanyRequest) (*CreateBusinessCompanyResponse, error)
}

// UnimplementedBusinessCompaniesServiceServer can be embedded to have forward compatible implementations.
type UnimplementedBusinessCompaniesServiceServer struct {
}

func (*UnimplementedBusinessCompaniesServiceServer) CreateBusinessCompany(ctx context.Context, req *CreateBusinessCompanyRequest) (*CreateBusinessCompanyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateBusinessCompany not implemented")
}

func RegisterBusinessCompaniesServiceServer(s *grpc.Server, srv BusinessCompaniesServiceServer) {
	s.RegisterService(&_BusinessCompaniesService_serviceDesc, srv)
}

func _BusinessCompaniesService_CreateBusinessCompany_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBusinessCompanyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BusinessCompaniesServiceServer).CreateBusinessCompany(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/businessCompanies.BusinessCompaniesService/CreateBusinessCompany",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BusinessCompaniesServiceServer).CreateBusinessCompany(ctx, req.(*CreateBusinessCompanyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _BusinessCompaniesService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "businessCompanies.BusinessCompaniesService",
	HandlerType: (*BusinessCompaniesServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateBusinessCompany",
			Handler:    _BusinessCompaniesService_CreateBusinessCompany_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "companies.proto",
}
